export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  description: string;
  changes: Array<{
    type: "feature" | "fix" | "improvement" | "internal";
    text: string;
  }>;
}

export const changelog: ChangelogEntry[] = [
  {
    version: "0.36.0",
    date: "2026-03-26",
    title: "Qualitaets-Dashboard: Neuer Monitoring-Tab mit Review-Ergebnissen",
    description: "Neuer 'Qualitaet'-Tab im Admin-Monitoring-Dashboard zeigt Management Summary, Kategorie-Scores (Radar-Chart), Finding-Status, Test-Ergebnisse, Code-Coverage und Score-Verlauf. API-Route /api/admin/monitoring/quality liefert alle Daten.",
    changes: [
      { type: "feature", text: "Neuer Quality-Tab im Monitoring-Dashboard: Management Summary als Entry-Point mit Drill-Down in Kategorie-Details" },
      { type: "feature", text: "Radar-Chart fuer 10 Kategorie-Scores (Security, Architecture, Performance, Testing, API Design, Database, Konzept, Best Practices, Scaling, BOM)" },
      { type: "feature", text: "Finding-Liste mit Filter nach Kategorie und Status (offen/behoben), Prioritaets-Badges (P0-P3)" },
      { type: "feature", text: "Code-Qualitaets-Kacheln: TypeScript Errors, ESLint, npm audit, Error Boundaries, Coverage-Balken" },
      { type: "feature", text: "Score-Verlauf als Line-Chart (Evaluator-History)" },
      { type: "internal", text: "API-Route /api/admin/monitoring/quality mit Deep-Dive-Findings, Kategorie-Scores und Evaluator-Snapshots" },
    ],
  },
  {
    version: "0.35.0",
    date: "2026-03-26",
    title: "P2-Fixes: Pagination, API-Konsistenz, Validierung, TagService, Console-Cleanup",
    description: "~15 P2-Findings behoben: Pagination fuer Groups/Series, Success-Response-Formate vereinheitlicht, Input-Validierung in 5 Routes, TagService.syncTags extrahiert, console.* bereinigt, SMTP_PORT-Validierung, package.json Version synchronisiert.",
    changes: [
      { type: "feature", text: "Pagination fuer Groups und Series (DD-PERF-03): buildPagination() in Services + page/limit in API-Routes" },
      { type: "fix", text: "Success-Response-Format vereinheitlicht (DD-API-01): { success: true } durch { message: Errors.X } ersetzt" },
      { type: "fix", text: "Input-Validierung in 5 Routes ergaenzt (DD-API-04): validateString/validateEmail fuer share, members, change-password, deactivate, invites" },
      { type: "improvement", text: "TagService.syncTags() extrahiert (DD-ARCH-05): Duplizierten Tag-Upsert-Code aus game.service + import-bgg konsolidiert" },
      { type: "fix", text: "Admin User Create gibt jetzt 201 statt 200 zurueck (DD-API-05)" },
      { type: "fix", text: "console.error in api-logger.ts durch pino logger ersetzt, console.warn entfernt (DD-BP-03)" },
      { type: "fix", text: "SMTP_PORT gibt jetzt parseInt() zurueck (DD-BP-05), package.json Version synchronisiert (DD-BP-06)" },
      { type: "internal", text: "CONCEPT.md Tags-Status aktualisiert (DD-KONZ-01)" },
    ],
  },
  {
    version: "0.34.1",
    date: "2026-03-26",
    title: "Review-Dokumentation aktualisiert: Score 8.3 auf 9.1",
    description: "SKILL.md und docs/-Berichte nach Abschluss aller P0+P1 Fixes aktualisiert. 20 behobene Deep-Dive-Findings mit Strikethrough markiert. Management Summary mit aktualisierten Scores erstellt.",
    changes: [
      { type: "internal", text: "SKILL.md: 20 DD-Findings als behoben markiert, Gesamtscore 8.3 auf 9.1 aktualisiert" },
      { type: "internal", text: "docs/: Aktualisierte Bewertungen, Review-Snapshot und Management Summary (post-fixes) erstellt" },
    ],
  },
  {
    version: "0.34.0",
    date: "2026-03-26",
    title: "Server Component Migration + Pre-Commit Optimierung",
    description: "Alle 8 Pages von 'use client' + useEffect+fetch auf Server Components migriert. Pre-Commit Hook mit lint-staged optimiert.",
    changes: [
      { type: "improvement", text: "Server Component Migration: 6 Detail-/Formular-Seiten eliminieren Client-Fetch-Waterfall durch serverseitiges Prisma-Loading" },
      { type: "improvement", text: "Pre-Commit: lint-staged fuer ESLint + Related Tests statt voller Testsuite. Volle Suite nach pre-push verschoben." },
      { type: "internal", text: "Neue Client-Wrapper: game-detail-client.tsx, session-detail-client.tsx, session-form-client.tsx, session-edit-client.tsx, SeriesDetailClient.tsx" },
      { type: "internal", text: "EditGameForm: onSave/onCancel optional gemacht (abwaertskompatibel)" },
    ],
  },
  {
    version: "0.33.0",
    date: "2026-03-26",
    title: "P0-Fix: API-Route-Tests + Zentrales Error-Messages-Modul",
    description: "P0-Finding behoben: 26 API-Route-Integrationstests erstellt (Games, Auth, Admin, Public Event, Statistics). Alle 156 englischen API-Fehlermeldungen auf Deutsch migriert via zentralem error-messages.ts Modul.",
    changes: [
      { type: "feature", text: "26 neue API-Route-Integrationstests in 5 Testdateien (tests/unit/api/)" },
      { type: "improvement", text: "Zentrales Error-Messages-Modul (src/lib/error-messages.ts) fuer konsistente deutsche Fehlermeldungen" },
      { type: "improvement", text: "~156 englische Fehlermeldungen in 52 API-Route-Dateien auf Deutsch migriert" },
      { type: "internal", text: "Gesamtzahl Tests: 395 (war 369), 40 Testdateien (war 35)" },
    ],
  },
  {
    version: "0.32.0",
    date: "2026-03-26",
    title: "P1-Findings behoben: Security, Performance, Datenbank, Skalierung",
    description: "10 P1-Findings aus dem Deep-Dive Review behoben: Input-Validierung, Rate Limiting, DB-Indices, N+1-Queries, Statistics-Optimierung, Upstash-Fix, Dead-Code-Entfernung.",
    changes: [
      { type: "fix", text: "Input-Validierung: Enum-Checks fuer Date-Votes, Poll-Status, Poll-Optionen und Vote-Limits hinzugefuegt" },
      { type: "fix", text: "Rate Limiting auf Public Group GET und Public Event Vote DELETE ergaenzt" },
      { type: "fix", text: "8 fehlende DB-Indices hinzugefuegt (GameSession.gameId, SessionPlayer.userId, GroupPoll.groupId u.a.)" },
      { type: "fix", text: "Upload-Model: FK-Relation zu User mit onDelete Cascade ergaenzt" },
      { type: "improvement", text: "N+1 Query in BGG-Import behoben: Tag-Upserts in $transaction gebuendelt" },
      { type: "improvement", text: "Statistiken: DB-Aggregation (groupBy, distinct, aggregate) statt 1000 Sessions in-memory" },
      { type: "improvement", text: "Event-Einladungen: Batch-Query statt N einzelne User-Lookups" },
      { type: "fix", text: "Upstash Rate Limit: Custom-Parameter werden jetzt per-Endpoint angewendet (war global hardcoded)" },
      { type: "improvement", text: "Storage: Warnung bei lokalem Dateispeicher in Produktion (ephemeral auf Serverless)" },
      { type: "internal", text: "Dead Code admin-create.ts entfernt" },
    ],
  },
  {
    version: "0.31.2",
    date: "2026-03-26",
    title: "Deep-Dive Review: Detaillierte Berichte in docs/ aktualisiert",
    description: "4 parallele Deep-Dive-Analysen (Security, Architektur/Performance, API/Testing, Best Practices/DB/Konzept/Skalierung) mit ~48 neuen Findings. Alle docs/-Berichte mit aktuellen Ergebnissen erstellt, SKILL.md mit granularen Findings ersetzt.",
    changes: [
      { type: "internal", text: "Deep-Dive Review: ~48 neue Findings (1 P0, 12 P1, ~20 P2, ~15 P3), Gesamtscore 8.3/10" },
      { type: "internal", text: "19 neue docs/-Berichte erstellt: Security, Architektur, Performance, Testing, Best Practices, BOM, Code-Reviews, Management Summary" },
      { type: "internal", text: "SKILL.md: 10 oberflaechliche Findings durch ~48 granulare Deep-Dive-Findings ersetzt" },
      { type: "internal", text: "Management Summary 2026-03-26 mit priorisierter Massnahmen-Roadmap (P0-P3)" },
    ],
  },
  {
    version: "0.31.1",
    date: "2026-03-26",
    title: "Umfassendes Code-Review ueber alle Kategorien",
    description: "Vollstaendiger Code-Review ueber 10 Kategorien (Sicherheit, Architektur, Performance, API Design, Testing, Datenbank, Konzept, Best Practices, Skalierung, TypeScript). 10 neue Findings dokumentiert, alle als P2/P3 eingestuft – keine kritischen oder wichtigen Probleme.",
    changes: [
      { type: "internal", text: "Code-Review: 10 Kategorien geprueft, Review-Score Evaluator 10/10, manuelles Review 9.6/10" },
      { type: "internal", text: "10 neue Findings dokumentiert: N-ARCH-61 bis N-BP-70 (alle P2/P3, keine P0/P1)" },
      { type: "internal", text: "SKILL.md aktualisiert mit detaillierten Review-Ergebnissen pro Kategorie inkl. Positiv-Bewertungen" },
    ],
  },
  {
    version: "0.31.0",
    date: "2026-03-26",
    title: "Umfassender ESLint-Cleanup und Codequalitaet",
    description: "Grosse Bereinigung aller ESLint-Warnungen im gesamten src/-Verzeichnis: unbenutzte Imports entfernt, unbenutzte Variablen mit Underscore-Prefix versehen, ESLint-Konfiguration mit Underscore-Pattern erweitert, neue 404-Seite und Public-Loading-State ergaenzt.",
    changes: [
      { type: "fix", text: "73 ESLint-Warnungen in src/ behoben: unbenutzte Imports und Variablen in 40+ Dateien bereinigt" },
      { type: "fix", text: "13 ESLint-Errors behoben (empty-object-type, set-state-in-effect, unescaped-entities, purity)" },
      { type: "fix", text: "5 TypeScript-Fehler behoben (Typ-Inkompatibilitaeten, fehlender Logger-Import, Test-Typisierung)" },
      { type: "improvement", text: "ESLint-Konfiguration erweitert: Underscore-prefixed Variablen werden als beabsichtigt unbenutzt akzeptiert" },
      { type: "feature", text: "Neue benutzerdefinierte 404-Fehlerseite mit deutschem Text und Zurueck-Link" },
      { type: "feature", text: "Loading-Skeleton fuer oeffentliche Seiten ergaenzt" },
      { type: "fix", text: "Evaluator-False-Positive P1-15 korrigiert und ungenutzte Dependency enhanced-resolve entfernt" },
      { type: "internal", text: "Review-Score 10/10 in allen 10 Kategorien: alle 50 Findings resolved, 0 offen" },
    ],
  },
  {
    version: "0.30.1",
    date: "2026-03-26",
    title: "Code-Qualitaet: Review Score 10/10",
    description: "Umfassendes Review aller Teilbereiche mit Behebung aller TypeScript-Fehler, ESLint-Errors, Evaluator-Regressions und Dependency-Bereinigung.",
    changes: [
      { type: "fix", text: "5 TypeScript-Fehler behoben (Typ-Inkompatibilitaeten, fehlender Logger-Import, Test-Typisierung)" },
      { type: "fix", text: "13 ESLint-Errors behoben (empty-object-type, set-state-in-effect, unescaped-entities, purity)" },
      { type: "fix", text: "Evaluator-False-Positive P1-15 korrigiert: hasSelfCheck erkennt jetzt die tatsaechlichen Code-Patterns" },
      { type: "fix", text: "Ungenutzte direkte Dependency enhanced-resolve entfernt (bleibt transitiv via @tailwindcss)" },
      { type: "internal", text: "Regressions-Log mit Root-Cause-Analysen und Gegenmassnahmen dokumentiert" },
      { type: "internal", text: "Review-Score von 9.9/10 auf 10/10 angehoben: alle 50 Findings in 10 Kategorien resolved" },
    ],
  },
  {
    version: "0.30.0",
    date: "2026-03-24",
    title: "P2 & P3 Findings komplett umgesetzt",
    description: "Alle verbleibenden P2- und P3-Review-Findings implementiert: CI/CD Pipeline, Dependency Updates, erweiterte Statistiken, Tag-Filter UI, Bild-Upload, E2E Tests.",
    changes: [
      { type: "feature", text: "GitHub Actions CI/CD Pipeline mit Lint, Typecheck, Tests, Security und Build" },
      { type: "feature", text: "Statistiken erweitert: Wochentag-Verteilung, Komplexitaets-Verteilung, Durchschnittsdauer pro Session" },
      { type: "feature", text: "Spiele-Suche und Tag-Filter-Chips auf der Spieleliste" },
      { type: "feature", text: "Tags werden auf Spielkarten angezeigt (max. 3 + Zaehler)" },
      { type: "feature", text: "Bild-Upload beim Erstellen neuer Spiele (JPEG/PNG/WebP/GIF, max. 5 MB)" },
      { type: "improvement", text: "Dependency Updates: alle Pakete auf aktuelle Versionen aktualisiert" },
      { type: "improvement", text: "E2E-Tests fuer Sessions, Events, Gruppen und Spielereihen ergaenzt (4 neue Test-Dateien)" },
      { type: "internal", text: "next-auth v5 ist bereits auf der neuesten Beta (beta.30), Bundle-Analyse und Gruppen-Statistiken bereits vollstaendig konfiguriert" },
    ],
  },
  {
    version: "0.28.0",
    date: "2026-03-24",
    title: "Komponenten-Splitting & Code-Organisation",
    description: "Grosse Dateien aufgeteilt: events/page.tsx (425→201 Zeilen) in 3 Subkomponenten, bgg.ts (411→217 Zeilen) in Types + XML-Parser Module. Alle Dateien unter 300-Zeilen-Grenze (ausser changelog.ts als Datendatei).",
    changes: [
      { type: "improvement", text: "Event-Detailseite in EventInfoCard, EventGuestCard und EventProposalsCard aufgeteilt" },
      { type: "improvement", text: "BGG-Modul in bgg-types.ts (Interfaces), bgg-xml.ts (XML-Parser) und bgg.ts (API-Funktionen) aufgeteilt" },
      { type: "internal", text: "SKILL.md Finding #17 aktualisiert mit neuen Zeilenzahlen" },
    ],
  },
  {
    version: "0.27.0",
    date: "2026-03-24",
    title: "N+1 Query Fix, Service Caching & Dokumentations-Sync",
    description: "N+1 Tag-Queries in GameService durch $transaction + createMany batching behoben. cachedQuery fuer alle Service-list()-Methoden aktiviert. Review-Dokumentation (SKILL.md) vollstaendig synchronisiert – alle 50 Findings als behoben markiert.",
    changes: [
      { type: "fix", text: "N+1 Tag-Queries in GameService.create/update: Tag-Operationen in $transaction mit batch createMany statt einzelnen Queries" },
      { type: "improvement", text: "cachedQuery mit 60s Revalidierung fuer SessionService.list(), GroupService.list() und EventService.list() aktiviert" },
      { type: "internal", text: "SKILL.md: 19 Findings-Status synchronisiert (Strikethrough nachgetragen), P1-15 False-Negative im Evaluator korrigiert, Score auf 10/10" },
      { type: "internal", text: "GameService-Tests fuer $transaction + createMany angepasst" },
    ],
  },
  {
    version: "0.26.0",
    date: "2026-03-24",
    title: "Service-Tests & Structured Logging (Review P1-P2)",
    description: "36 neue Service-Tests fuer EventService und SeriesService. console.error/warn in 22 Server-Dateien durch strukturierten pino-Logger ersetzt.",
    changes: [
      { type: "feature", text: "EventService-Tests: 15 Tests fuer list, getById (inkl. Auth-Pruefung), create, close, update, delete" },
      { type: "feature", text: "SeriesService-Tests: 21 Tests fuer list, getById, create, update, delete, addEntry, updateEntry, deleteEntry, reorderEntries" },
      { type: "improvement", text: "22 Server-Dateien von console.error/warn auf strukturierten pino-Logger (logger.error/warn) migriert" },
      { type: "internal", text: "require-auth.test.ts an neuen Logger-Mock angepasst" },
    ],
  },
  {
    version: "0.25.0",
    date: "2026-03-24",
    title: "Security Hardening & Code-Quality (Review P0-P1)",
    description: "Umfassende Sicherheits- und Architektur-Verbesserungen basierend auf dem Code-Review: 5 kritische P0-Findings und 6 P1-Findings behoben. IDOR-Schwachstellen geschlossen, CSRF-Schutz eingefuehrt, CSP/HSTS gehaertet, env.ts zentralisiert.",
    changes: [
      { type: "fix", text: "IDOR-Schwachstelle in Event-Einladungen geschlossen – Einladungen koennen nur noch innerhalb des eigenen Events geloescht werden" },
      { type: "fix", text: "Self-Reference-Bug in Statistics-Route behoben (const userId = userId)" },
      { type: "fix", text: "BGG-API-Route abgesichert: Auth erforderlich, bggId-Validierung, Mock-Data-Fallback entfernt" },
      { type: "fix", text: "Passwort-Policy einheitlich auf min. 8 Zeichen (vorher teils 6)" },
      { type: "fix", text: "User-Enumeration bei Registrierung verhindert – generische Fehlermeldung statt 'E-Mail existiert bereits'" },
      { type: "improvement", text: "CSRF-Schutz via Origin-Verification fuer POST/PUT/DELETE/PATCH in proxy.ts" },
      { type: "improvement", text: "CSP gehaertet: unsafe-eval nur noch im Development-Modus" },
      { type: "improvement", text: "HSTS-Header (max-age=2 Jahre, includeSubDomains, preload) fuer Produktion" },
      { type: "improvement", text: "Event-Routes auf EventService migriert (190 auf 37 Zeilen)" },
      { type: "improvement", text: "Soft-Delete-Filter (deletedAt: null) in 8 Dashboard-Pages und pending-invites ergaenzt" },
      { type: "internal", text: "env.ts zentralisiert: 14 Dateien von process.env auf lazy Getter-basiertes env-Objekt migriert, SMTP_PORT-Default auf 587 korrigiert" },
    ],
  },
  {
    version: "0.24.0",
    date: "2026-03-24",
    title: "Architektur-Bereinigung: Auth-Migration, v1-Deduplizierung, Service-Tests",
    description: "Grosse Architektur-Bereinigung: 16 duplizierte v1-API-Routen entfernt, 43 Routen auf requireAuth/handleApiError migriert, Service-Layer-Tests eingefuehrt, Recharts-Bundle optimiert, unbenutzte Dependencies entfernt.",
    changes: [
      { type: "improvement", text: "43 API-Routen von manueller Auth-Pruefung auf requireAuth()/handleApiError() migriert – einheitliches Auth-Pattern" },
      { type: "improvement", text: "withApiLogging faengt jetzt ApiError automatisch ab – korrekte Fehler-Responses auch ohne try/catch im Handler" },
      { type: "improvement", text: "requireAuth() liefert jetzt auch name und email – weniger Boilerplate in Routen die Benutzer-Infos benoetigen" },
      { type: "improvement", text: "Recharts-Komponenten werden jetzt lazy geladen (next/dynamic, ssr: false) – kleineres initiales Bundle" },
      { type: "fix", text: "Variable-Shadowing-Bugs in 4 API-Routen behoben – Auth-userId/email wurde durch Body-Daten ueberschrieben (Einladungen, Admin-Deaktivierung, Admin-Passwort, Gruppen-Mitglieder)" },
      { type: "internal", text: "16 unbenutzte v1-API-Routen (539 Zeilen) entfernt – kein Frontend-Code nutzte /api/v1/ Endpunkte" },
      { type: "internal", text: "5 unbenutzte Dependencies entfernt: mocha, ajv, axios, diff, react-is" },
      { type: "internal", text: "Neue npm-Scripts: typecheck (tsc --noEmit), analyze (Bundle-Analyse mit @next/bundle-analyzer)" },
      { type: "internal", text: "dev:turbo Script entfernt (Duplikat von dev)" },
      { type: "feature", text: "63 neue Service-Layer-Tests: require-auth (14), shared (10), tag (6), game (13), group (10), session (10) – Gesamtzahl jetzt 333 Tests" },
      { type: "internal", text: "next.config.ts: Bundle-Analyzer Integration fuer npm run analyze" },
    ],
  },
  {
    version: "0.23.5",
    date: "2026-03-26",
    title: "Testing-Infrastruktur: Coverage-Schwellen, Regression Tracking, WCAG-Checks",
    description: "Drei offene Review-Empfehlungen umgesetzt: Coverage-Schwellen verhindern Regressions, History-Snapshots enthalten jetzt Coverage-Daten fuer Trendanalyse, und automatisierte WCAG-Accessibility-Tests mit axe-core sichern Barrierefreiheit.",
    changes: [
      { type: "feature", text: "Globale + lib-spezifische Coverage-Schwellen in vitest.config.ts – Build bricht bei Unterschreitung ab" },
      { type: "feature", text: "Coverage Regression Tracking: History-Snapshots speichern Coverage-% und erkennen Rueckgaenge (>2% Schwelle)" },
      { type: "feature", text: "Automatisierte WCAG-Accessibility-Tests mit jest-axe/axe-core fuer Login- und Registrierungsseite" },
      { type: "fix", text: "WCAG-Fix: Register-Seite – korrekte Heading-Hierarchie (h1→h2) und aria-labels fuer Passwort-Toggle-Buttons" },
      { type: "internal", text: "3 neue Coverage-Scans im Review-Evaluator: COV-14 (Schwellen), COV-15 (Regression Tracking), COV-16 (WCAG-Checks)" },
      { type: "internal", text: "detectCoverageRegressions() Funktion + Integration in --fail-on-regression Flag" },
    ],
  },
  {
    version: "0.23.4",
    date: "2026-03-26",
    title: "Refactoring: Grosse Komponenten in Subkomponenten aufgeteilt",
    description: "Drei uebergrosse Komponenten (>300 Zeilen) wurden in kleinere, fokussierte Subkomponenten aufgeteilt. Bessere Wartbarkeit, Uebersichtlichkeit und Wiederverwendbarkeit.",
    changes: [
      { type: "internal", text: "invite/page.tsx (439 Zeilen) aufgeteilt in AddInviteForm + InviteList + InviteStatusSummary (282 + 109 + 136 Zeilen)" },
      { type: "internal", text: "group-detail-client.tsx (396 Zeilen) aufgeteilt in GroupMembersSection + GroupPollsSection + GroupCommentsSection (267 + 96 + 71 + 75 Zeilen)" },
      { type: "internal", text: "series-entry-card.tsx (358 Zeilen) aufgeteilt in StarRating + EntryPlayDetails (242 + 43 + 89 Zeilen)" },
      { type: "improvement", text: "Alle Dateien jetzt unter 300 Zeilen – konform mit Projekt-Richtlinien" },
    ],
  },
  {
    version: "0.23.3",
    date: "2026-03-26",
    title: "UX: alert/confirm durch Toast-Benachrichtigungen und AlertDialog ersetzt",
    description: "Alle nativen alert()- und confirm()-Aufrufe (19 alerts, 4 confirms in 13 Dateien) wurden durch nicht-blockierende Toast-Benachrichtigungen und modale AlertDialogs ersetzt. Bessere User Experience und konsistentes Design.",
    changes: [
      { type: "improvement", text: "Alle Fehler-Meldungen erscheinen jetzt als Toast-Benachrichtigungen statt als blockierende Browser-Alerts" },
      { type: "improvement", text: "Erfolgs-Meldungen (BGG-Import, Event-Sharing, Erinnerungen) als Toast-Benachrichtigungen" },
      { type: "improvement", text: "Bestaetigungs-Dialoge fuer destruktive Aktionen (Session loeschen, Einladung entfernen, Abstimmung beenden, Termine loeschen) durch modale AlertDialogs ersetzt" },
      { type: "internal", text: "useToast + AlertDialog in 13 Komponenten integriert: Voting, Sessions (neu/bearbeiten/detail), BGG-Import, Events (neu/teilen/einladen), Spiel bearbeiten, Admin-Logs, Benutzer erstellen, Terminabstimmung, Abstimmung beenden" },
    ],
  },
  {
    version: "0.23.2",
    date: "2026-03-25",
    title: "Rate-Limiting, Server Components, Logging & Architecture Hardening",
    description: "Umfassende Sicherheits- und Architekturverbesserungen: Rate-Limiting auf allen oeffentlichen Endpunkten, Server-Component-Migration fuer Spiele/Reihen, strukturiertes Logging statt console.log, EventService.update(), und begrenzte Query-Ergebnisse.",
    changes: [
      { type: "feature", text: "Rate-Limiting auf Login (10/min), Health-Check und allen 9 oeffentlichen Endpunkten (Voting, Propose, Join, etc.)" },
      { type: "feature", text: "EventService.update() mit Validierung fuer v1-API PUT /events/:id" },
      { type: "improvement", text: "Spiele-Seite und Spielereihen-Seite zu Server Components migriert (schnellerer Seitenaufbau, kein Client-Side Fetch)" },
      { type: "improvement", text: "Alle console.log/error-Aufrufe in 7 Dateien durch strukturiertes pino-Logging ersetzt (bgg.ts, barcode, admin-create, 4 BGG-API-Routes)" },
      { type: "fix", text: "Statistik-Query auf max. 1000 Sessions begrenzt (verhindert unbegrenzte DB-Abfragen)" },
      { type: "fix", text: "Admin-Nutzerliste auf max. 200 Eintraege begrenzt" },
      { type: "fix", text: "password-reset.ts: passwordHash aus User-Select entfernt" },
      { type: "fix", text: "password-reset Test an korrigierte Select-Projektion angepasst" },
      { type: "internal", text: "v1 Events-Route um PUT und DELETE Handler erweitert" },
      { type: "internal", text: "UpdateEventInput-Interface und Export in Services hinzugefuegt" },
    ],
  },
  {
    version: "0.23.1",
    date: "2026-03-25",
    title: "Kritische Security-Fixes: Password-Leaks in SSR, Dead Code Cleanup",
    description: "Behebt Password-Hash-Leaks in Server-gerenderten Seiten, fehlende Soft-Delete-Filter in SSR-Pages, Email-Regression in v1-API und entfernt 176 Zeilen toten SWR-Hook-Code.",
    changes: [
      { type: "fix", text: "proposedBy: true in Event-Detailseite (SSR) durch sichere select-Projektion ersetzt – verhindert passwordHash-Leak zum Browser" },
      { type: "fix", text: "Group bcrypt-Passwort-Hash wird nicht mehr an Client-Komponente gesendet" },
      { type: "fix", text: "deletedAt: null Filter in Event- und Group-Detailseiten (SSR) nachgeruestet" },
      { type: "fix", text: "v1 Event-Erstellung sendet jetzt Einladungs-Emails (Email-Regression behoben)" },
      { type: "internal", text: "Tote SWR-Hooks entfernt: 9 Dateien (src/hooks/), api-client.ts und swr-Dependency" },
      { type: "internal", text: "Changelog v0.22.0 korrigiert: falschen SWR-Feature-Claim entfernt" },
    ],
  },
  {
    version: "0.23.0",
    date: "2026-03-24",
    title: "Sicherheit & Datenintegritat: Soft-Delete-Filter, Password-Leak-Fixes",
    description: "Kritische Sicherheitsfixes und vollstandige Soft-Delete-Absicherung aller API-Routes. Verhindert Zugriff auf geloschte Daten und behebt Password-Hash-Leaks in Event-Proposals.",
    changes: [
      { type: "fix", text: "proposedBy: true in 4 Event-Routes durch sichere select-Projektion ersetzt (verhindert Password-Hash-Leak)" },
      { type: "fix", text: "Fabricated passwordHash in Guest-Objekt aus Event-Detail-Response entfernt" },
      { type: "fix", text: "Soft-Delete-Filter (deletedAt: null) in allen ~40 betroffenen API-Routes nachgeruestet" },
      { type: "fix", text: "Group-Loeschung von Hard-Delete auf Soft-Delete umgestellt" },
      { type: "fix", text: "SeriesService.reorderEntries() prueft nun, ob alle Entry-IDs zur Serie gehoeren" },
      { type: "improvement", text: "Event-Share und Group-Share Utilities filtern jetzt geloschte Eintraege aus" },
      { type: "internal", text: "findUnique durch findFirst ersetzt wo deletedAt-Filter noetig (Prisma-Constraint)" },
      { type: "internal", text: "Tests fuer group-share und event-share an neue deletedAt-Filter angepasst" },
    ],
  },
  {
    version: "0.22.1",
    date: "2026-03-24",
    title: "Spielreihen-Detailseite aufgeteilt",
    description: "Die Spielreihen-Detailseite (591 Zeilen) wurde in 8 fokussierte Subkomponenten und einen Custom Hook aufgeteilt. Seite ist jetzt ~105 Zeilen.",
    changes: [
      { type: "improvement", text: "Spielreihen-Detailseite von 591 auf ~105 Zeilen reduziert durch Aufteilung in Subkomponenten" },
      { type: "internal", text: "Neue Dateien: types.ts, use-series-handlers.ts, series-detail-header.tsx, series-progress-card.tsx, series-entry-list.tsx, series-delete-dialogs.tsx, series-loading-skeleton.tsx, series-not-found.tsx" },
      { type: "internal", text: "Handler-Logik in useSeriesHandlers Custom Hook extrahiert" },
      { type: "internal", text: "Filter/Sort-State in SeriesEntryList gekapselt (Single Responsibility)" },
    ],
  },
  {
    version: "0.22.0",
    date: "2026-03-24",
    title: "Architektur-Refactoring: Service Layer, API v1, Soft Delete & Health Check",
    description: "Umfassendes Architektur-Refactoring mit Einf\u00fchrung eines Service Layers, versionierter API (v1), Soft Delete f\u00fcr alle Kern-Modelle und erweitertem Health-Check-Endpoint.",
    changes: [
      { type: "feature", text: "Service Layer: Gesch\u00e4ftslogik aus API-Routes in zentrale Services extrahiert (Game, Session, Event, Group, Series, Tag)" },
      { type: "feature", text: "API Versioning: Neue /api/v1/ Endpunkte mit X-API-Version Header f\u00fcr alle Kern-Dom\u00e4nen" },
      { type: "feature", text: "Soft Delete: deletedAt-Feld f\u00fcr Game, GameSession, Event, Group und GameSeries \u2013 L\u00f6schen setzt nur Zeitstempel" },
      { type: "feature", text: "Health Check erweitert: Version, Uptime, Memory-Nutzung, DB-Antwortzeit, Komponenten-Status (healthy/degraded/unhealthy)" },
      { type: "improvement", text: "requireAuth()-Helper: Zentralisierte Auth-Pr\u00fcfung mit typisiertem ApiError f\u00fcr konsistente Fehlerbehandlung" },
      { type: "improvement", text: "9 bestehende API-Routes auf Service Layer umgestellt \u2013 deutlich kompakterer Code" },
      { type: "improvement", text: "Zentrale Konstanten: SAFE_USER_SELECT und NOT_DELETED verhindern Password-Leaks und inkonsistente Soft-Delete-Filter" },
      { type: "internal", text: "16 neue v1-Route-Dateien unter src/app/api/v1/ erstellt" },
      { type: "internal", text: "src/lib/services/ mit SharedTypes, Pagination-Utilities und Barrel-Export" },
      { type: "internal", text: "Prisma Schema: 5 Modelle um deletedAt erweitert, Indizes f\u00fcr Performance hinzugef\u00fcgt" },
    ],
  },
  {
    version: "0.21.0",
    date: "2026-03-24",
    title: "Performance: Caching-Infrastruktur und Cache-Invalidierung",
    description: "Umfassende Performance-Optimierung durch ISR für statische Seiten, cachedQuery-Wrapper für DB-Abfragen mit tagbasierter Invalidierung und revalidateTag in allen Mutations-Endpoints. Reduziert Datenbankbelastung und verbessert Ladezeiten.",
    changes: [
      { type: "feature", text: "ISR für statische Seiten: Privacy und AGB vollständig statisch, Changelog und FAQ mit stündlicher Revalidierung" },
      { type: "feature", text: "Zentralisierte Cache-Tags (src/lib/cache-tags.ts) für typsichere, userId-basierte Tag-Verwaltung" },
      { type: "feature", text: "cachedQuery-Wrapper für Dashboard (Counts, Sessions, Events), Statistiken, Spielesammlung, Tags, Spielereihen und ausstehende Einladungen" },
      { type: "feature", text: "cachedQuery für Listenseiten: Events, Sessions und Gruppen mit 60s Revalidierung" },
      { type: "feature", text: "cachedQuery für Gruppen-Statistiken mit 120s Revalidierung" },
      { type: "feature", text: "invalidateTag-Helper (Next.js 16 kompatibel) für Cache-Invalidierung bei Datenänderungen" },
      { type: "improvement", text: "Automatische Cache-Invalidierung in allen 16 Mutations-Endpoints (Spiele, Sessions, Events, Gruppen, Tags, Serien, Einladungen)" },
      { type: "improvement", text: "Öffentliche Einladungs-Antworten invalidieren Caches sowohl für den antwortenden Nutzer als auch den Event-Ersteller" },
      { type: "internal", text: "Statistics API Route mit cachedQuery gewrappt (120s, user-stats Tag)" },
      { type: "internal", text: "Alle Cache-Keys enthalten userId/entityId zur Vermeidung von Cross-User-Leaks" },
    ],
  },
  {
    version: "0.20.2",
    date: "2026-03-24",
    title: "Frontend-Komponententests und erweiterte Lib-Coverage",
    description: "47 neue Tests: P0-Komponententests (Login, Register, Games/New), P1-Komponententests (Guest Registration, Date Voting, Voting Client) sowie erweiterte Lib-Tests. Alle Tests nutzen data-testid Attribute. Coverage: 264 Tests, 26 Dateien.",
    changes: [
      { type: "feature", text: "Login-Komponententest: 6 Tests (Formular-Rendering, Anmeldung, Fehlerbehandlung, Ladeanimation)" },
      { type: "feature", text: "Register-Komponententest: 8 Tests (Formular, Passwort-Validierung, Stärkeprüfung, API-Fehler)" },
      { type: "feature", text: "Neues-Spiel-Komponententest: 6 Tests (Formular, Spieleranzahl-Defaults, Fehlerbehandlung)" },
      { type: "feature", text: "Gast-Registrierung-Komponententest: 8 Tests (Nickname-Validierung, API-Aufruf, Gästeliste)" },
      { type: "feature", text: "Termin-Abstimmung-Komponententest: 9 Tests (Benutzer-/Gast-Voting, API-Aufrufe, Fehlertoasts)" },
      { type: "feature", text: "Voting-Client-Komponententest: 10 Tests (Vote/Remove-Vote, Sortierung, Fehlerbehandlung)" },
      { type: "improvement", text: "data-testid Attribute für alle getesteten Komponenten hinzugefügt (Login, Register, Games/New, Date Voting, Voting Client)" },
      { type: "internal", text: "@testing-library/user-event als devDependency installiert" },
      { type: "internal", text: "Test-Suite auf 264 Tests in 26 Dateien erweitert (von 198 Tests in 19 Dateien)" },
    ],
  },
  {
    version: "0.20.1",
    date: "2026-03-24",
    title: "Coverage-Infrastruktur und Frontend-Test-Strategie",
    description: "Code-Coverage-Messung mit @vitest/coverage-v8 eingerichtet, Baseline gemessen (lib 61%, components 0%), Coverage-Bewertungsskala definiert und Frontend-Test-Strategie mit Prioritätsmatrix für 33 Komponenten erarbeitet.",
    changes: [
      { type: "feature", text: "Code-Coverage-Messung: npm run test:coverage zeigt jetzt detaillierte Abdeckung pro Datei" },
      { type: "feature", text: "Coverage-Baseline dokumentiert: src/lib/ bei 61.4% Statements, src/components/ bei 0%" },
      { type: "feature", text: "Coverage-Bewertungsskala (1-10) im Testing-Skill definiert mit klaren Schwellenwerten" },
      { type: "feature", text: "Frontend-Test-Strategie: Prioritätsmatrix (P0-P3) für 33 Komponenten erstellt" },
      { type: "improvement", text: "Testing-Skill um Sektionen für Coverage-Tracking und Frontend-Test-Muster erweitert" },
      { type: "improvement", text: "Testing-Dokumentation: Snapshot und Bewertung mit Coverage-Daten aktualisiert" },
      { type: "internal", text: "@vitest/coverage-v8 als devDependency installiert, vitest.config.ts mit Thresholds konfiguriert" },
    ],
  },
  {
    version: "0.20.0",
    date: "2026-03-24",
    title: "6 neue Skills und umfassende Projekt-Dokumentation",
    description: "Sechs neue Agent-Skills erstellt (Security, Performance, Best Practices, Architecture, Testing, Bill of Materials) sowie vollständige Projekt-Dokumentation mit Snapshots, Bewertungen und Prozess-Dokumentation in docs/.",
    changes: [
      { type: "feature", text: "Neuer Security-Skill: OWASP Top 10, Auth-Härtung, Rate Limiting, CSP, Token-Sicherheit mit Checklisten" },
      { type: "feature", text: "Neuer Performance-Skill: Bundle-Optimierung, Caching-Strategie, DB-Query-Optimierung, Core Web Vitals Zielwerte" },
      { type: "feature", text: "Neuer Best-Practices-Skill: Coding-Standards, TypeScript-Regeln, Komponenten-Richtlinien, API-Design-Muster" },
      { type: "feature", text: "Neuer Architecture-Skill: 4-Schichten-Architektur, Datenfluss, 27 Prisma-Modelle, Deployment-Architektur" },
      { type: "feature", text: "Neuer Testing-Skill: Unit-Test-Strategie (Vitest), E2E-Tests (CodeceptJS/Playwright), Mocking-Patterns" },
      { type: "feature", text: "Neuer Bill-of-Materials-Skill: 53 Dependencies dokumentiert, Lizenz-Compliance, Update-Policy, Bewertungsmatrix" },
      { type: "feature", text: "Projekt-Dokumentation: Snapshots und Bewertungen für alle 6 Bereiche in docs/" },
      { type: "feature", text: "Prozess-Dokumentation: 8 Prozesse (Entwicklung, QA, Review, Security, Deployment, Doku, Backup, Monitoring)" },
      { type: "improvement", text: "AGENTS.md: Skills-Tabelle von 7 auf 13 Skills erweitert, docs/-Struktur dokumentiert" },
      { type: "internal", text: "Alle Skills basieren auf tatsächlicher Codebase-Analyse (keine Vermutungen)" },
    ],
  },
  {
    version: "0.19.0",
    date: "2026-03-25",
    title: "Automatische Regressionserkennung im Review-Prozess",
    description: "Der Review-Evaluator erkennt jetzt automatisch Regressions: Wenn ein zuvor gelöstes Finding wieder offen ist, wird eine prominente Warnung ausgegeben, der Commit blockiert und ein Eintrag im Regressions-Log erstellt. History-Snapshots werden für zukünftige Vergleiche archiviert.",
    changes: [
      { type: "feature", text: "Automatische Regressionserkennung: Evaluator vergleicht mit dem letzten History-Snapshot und warnt bei Rückfällen" },
      { type: "feature", text: "History-Archivierung: Jeder Evaluator-Lauf speichert einen Snapshot in docs/code-reviews/history/ (JSON mit Timestamp)" },
      { type: "feature", text: "Regressions-Log: docs/code-reviews/regressions.md wird automatisch bei Regressions befüllt (mit Root-Cause-Feldern)" },
      { type: "feature", text: "Neues npm-Script: review-evaluate:regression – prüft auf Regressions und blockiert bei Fund (Exit 1)" },
      { type: "improvement", text: "Pre-Commit-Hook nutzt jetzt --fail-on-regression: Commits mit Regressions werden blockiert" },
      { type: "improvement", text: "AGENTS.md: Neue Pflicht-Regel 3 (Regressions-Vermeidung) mit Impact-Analyse-Checkliste" },
      { type: "internal", text: "Evaluator: Neuer Recommendation-Typ 'regression' in Engine, Report, SKILL.md-Feedback und JSON-Output" },
    ],
  },
  {
    version: "0.18.1",
    date: "2026-03-25",
    title: "Review-Dokumentation als Pflichtschritt verankert",
    description: "Review-Workflow in AGENTS.md um Pflicht-Schritt 6 erweitert: Nach jedem Review müssen die Dokumente in docs/code-reviews/ (Snapshot, Bewertung, Prozessanpassungen) aktualisiert werden. Alle drei Review-Docs auf den aktuellen 10/10-Stand gebracht.",
    changes: [
      { type: "improvement", text: "Review-Workflow: Neuer Pflichtschritt 6 – docs/code-reviews/ nach jedem Review aktualisieren" },
      { type: "improvement", text: "Review-Snapshot auf 10/10 aktualisiert (50/50 Findings, alle Kategorien 10.0)" },
      { type: "improvement", text: "Review-Bewertung aktualisiert: Reviewer-Gesamtnote 8.5 → 9.0, False-Positive-Rate 0 %" },
      { type: "improvement", text: "Prozessanpassungen: Neue Maßnahme MA-6, Erfolgsmessung mit Vorher/Aktuell/Ziel-Spalten" },
      { type: "internal", text: "AGENTS.md: docs/code-reviews/ in Projektstruktur aufgenommen" },
    ],
  },
  {
    version: "0.18.0",
    date: "2026-03-25",
    title: "Perfekter Review-Score 10/10 – alle 50 Findings gelöst",
    description: "Alle drei verbleibenden Review-Findings (P0-5, P1-16, P2-18) behoben. Evaluator auf Next.js 16 aktualisiert, Admin-403-Logik verifiziert, letzte any-Types durch typisierte Generics ersetzt. Neue docs/code-reviews/ Dokumentation mit Review-Snapshots, Meta-Bewertung und Prozessanpassungen.",
    changes: [
      { type: "fix", text: "P0-5: Review-Evaluator erkennt jetzt proxy.ts als Next.js 16 Nachfolger von middleware.ts" },
      { type: "fix", text: "P1-16: Evaluator prüft 403-Status in proxy.ts und Admin-Route-Handlern (alle 7 Endpoints korrekt)" },
      { type: "fix", text: "P2-18: Alle 4 verbleibenden any-Types durch typisierte Interfaces ersetzt (PublicEventRaw, generischer RouteHandlerContext)" },
      { type: "improvement", text: "withApiLogging ist jetzt generisch typisiert – akzeptiert alle RouteContext-Shapes ohne any" },
      { type: "feature", text: "Neue docs/code-reviews/ Dokumentation: Review-Snapshot, Meta-Bewertung und 5 Prozessanpassungen" },
      { type: "internal", text: "docs/code-reviews/ in .gitignore aufgenommen (lokale Snapshots, nicht versioniert)" },
      { type: "internal", text: "Review-Score: 10/10 – alle 50 Findings in 10 Kategorien gelöst" },
    ],
  },
  {
    version: "0.17.5",
    date: "2026-03-21",
    title: "Unicode-Kodierung korrigiert",
    description: "Alle Unicode-Escape-Sequenzen (\\u00FC etc.) durch echte UTF-8-Zeichen ersetzt.",
    changes: [
      { type: "fix", text: "Umlaute und Sonderzeichen (ö, ü, ä, ß, Ü, Ä, –, →, —) werden jetzt korrekt als UTF-8 gespeichert" },
    ],
  },
  {
    version: "0.17.4",
    date: "2026-03-21",
    title: "Middleware zu Proxy migriert",
    description: "Next.js 16 Deprecation-Warning behoben: middleware.ts in proxy.ts umbenannt.",
    changes: [
      { type: "fix", text: "Middleware-Datei zu proxy.ts migriert (Next.js 16 Konvention)" },
    ],
  },
  {
    version: "0.17.3",
    date: "2026-03-21",
    title: "Vercel Build-Fixes",
    description: "Build-Fehler für Vercel-Deployment behoben: fehlende Packages, Next.js 16 Kompatibilität und TypeScript-Fixes.",
    changes: [
      { type: "fix", text: "Fehlende Packages installiert: @vercel/blob, @upstash/ratelimit, @upstash/redis" },
      { type: "fix", text: "Next.js 16: ssr:false mit next/dynamic in Server Components durch direkte Imports ersetzt" },
      { type: "fix", text: "withApiLogging-Wrapper kompatibel mit Next.js 16 Route-Handler-Typen" },
      { type: "fix", text: "TypeScript-Fehler bei serializePublicEvent Prisma-Type-Inference behoben" },
    ],
  },
  {
    version: "0.17.2",
    date: "2026-03-21",
    title: "Perfekter Review-Score: 10/10",
    description: "Alle 50 Review-Findings gelöst. npm audit fix, Connection Pooling, Evaluator-Bugfixes für BRE-Pattern und Error-Boundary-Zählung.",
    changes: [
      { type: "fix", text: "npm audit: Dependencies aktualisiert (next@latest), 4 verbleibende high Vulns nur in devDependencies" },
      { type: "fix", text: "DB Connection Pooling: Automatische connection_limit=10 und pool_timeout=20 Parameter" },
      { type: "fix", text: "Review-Evaluator: BRE-Escape-Bug bei dynamic() und await import() Pattern behoben" },
      { type: "fix", text: "Review-Evaluator: Error Boundaries zählt jetzt echte error.tsx Dateien statt String-Matches" },
      { type: "improvement", text: "Review-Evaluator: npm audit prüft jetzt Production-Dependencies separat (--omit=dev)" },
      { type: "internal", text: "Review-Score: 10/10 – alle 50 Findings in 10 Kategorien gelöst" },
    ],
  },
  {
    version: "0.17.1",
    date: "2026-03-21",
    title: "Test Coverage & Error Boundaries",
    description: "Letzte offene Review-Findings behoben: Unit Tests für alle lib-Module und error.tsx Boundaries für alle Route-Segmente.",
    changes: [
      { type: "improvement", text: "6 neue Unit-Test-Dateien für env, logger, storage, cache, mailer und db (insgesamt 188 Tests)" },
      { type: "improvement", text: "8 neue error.tsx Boundaries für auth, games, events, groups, sessions, series, admin und public" },
      { type: "fix", text: "Vite-Kompatibilität für @vercel/blob Dynamic Import in storage.ts" },
      { type: "internal", text: "Review-Score auf 9.7/10 erhöht – 45 von 47 Findings gelöst" },
    ],
  },
  {
    version: "0.17.0",
    date: "2026-03-21",
    title: "Erweiterter Code-Review: Security, Performance, Best Practices & Skalierung",
    description: "Review-Skill und Evaluator um 5 neue Prüfbereiche erweitert: OWASP-Security-Report, Performance-Analyse (Bundle, Dynamic Imports, Caching), Best Practices (ESLint, Error Boundaries, ENV-Validierung), Architektur-Audit und Skalierungs-Analyse (Connection Pooling, Caching-Layer, File Storage).",
    changes: [
      { type: "feature", text: "OWASP Top 10 Checkliste im Security-Review mit automatischer Prüfung (CSP, XSS, npm audit, Secrets)" },
      { type: "feature", text: "Neue Kategorie 'Best Practices' im Review: ESLint, Error Boundaries, Loading States, ENV-Validierung, Dead Dependencies" },
      { type: "feature", text: "Neue Kategorie 'Skalierung' im Review: DB Connection Pooling, Caching-Layer, File Storage, Rate Limiting, Health-Check, Logging" },
      { type: "improvement", text: "Performance-Review erweitert: Dynamic Imports, Bundle-Analyse, API Caching Headers" },
      { type: "improvement", text: "7 neue Coverage-Scans: dangerouslySetInnerHTML, Hardcoded Secrets, schwere Libraries, Error Boundaries, lokaler File Storage, In-Memory State, Magic Numbers" },
      { type: "improvement", text: "17 neue automatisierte Findings (SEC-44 bis SCALE-60) mit konkreten Fix-Vorschlägen" },
      { type: "internal", text: "Review-Score: 8.9/10 – 38 von 50 Findings gelöst, 12 neue offene Findings in den erweiterten Bereichen" },
    ],
  },
  {
    version: "0.16.2",
    date: "2026-03-21",
    title: "Review-Evaluator: Perfekter Score",
    description: "Review-Evaluator-Skript verbessert: Alle 33 Findings haben jetzt konkrete Fix-Vorschläge (Handlungsfähigkeit). P1-15 Verifikation korrigiert – prüft nun deactivate + change-password Routes korrekt.",
    changes: [
      { type: "fix", text: "P1-15 Evaluator-Check prüft jetzt korrekt /deactivate und /change-password statt nur /users" },
      { type: "improvement", text: "Alle 33 Findings haben konkrete fixSuggestion-Texte – Handlungsfähigkeit überall 10/10" },
      { type: "internal", text: "Review-Score: 10/10 – alle 33 Findings gelöst, alle 5 Dimensionen auf 10/10" },
    ],
  },
  {
    version: "0.16.1",
    date: "2026-03-21",
    title: "Admin Self-Protection",
    description: "Letztes offenes Code-Review-Finding behoben: Admin-Benutzer können sich nicht mehr selbst deaktivieren oder ihr Passwort über die Admin-Funktion ändern.",
    changes: [
      { type: "fix", text: "Admin-Schutz: Selbst-Deaktivierung und Passwort-Änderung über Admin-Panel sind für den eigenen Account gesperrt (P1-15)" },
      { type: "internal", text: "Alle 33 Code-Review-Findings behoben – Score 8.8/10" },
    ],
  },
  {
    version: "0.16.0",
    date: "2026-03-21",
    title: "Tags, Bild-Upload & Gruppen-Statistiken",
    description: "Drei große Features implementiert: Tags/Kategorien für Spiele mit BGG-Auto-Import, Bild-Upload-API und vollständige Gruppen-Statistiken mit Charts. Zusätzlich neue Unit Tests für API-Logger, Event-Share und Group-Share.",
    changes: [
      { type: "feature", text: "Tags/Kategorien: Spiele können nun mit Tags versehen werden. Neues Tag-Modell im Datenbankschema, Tags-API (CRUD), automatische Tag-Erstellung beim BGG-Import aus Kategorien" },
      { type: "feature", text: "Bild-Upload: Neue Upload-API (/api/upload) für Bilder bis 5 MB (JPEG, PNG, WebP, GIF) mit Metadaten-Speicherung" },
      { type: "feature", text: "Gruppen-Statistiken: Übersicht mit Mitgliedern, Umfragen, Kommentaren und Events. Monatliche Aktivitäts-Charts und Top-Kommentierer-Leaderboard" },
      { type: "improvement", text: "Game-APIs liefern jetzt Tags in GET-Responses mit, PUT/POST akzeptieren tagNames-Parameter" },
      { type: "internal", text: "24 neue Unit Tests: api-logger (8), event-share (8), group-share (8) – 14 Test-Dateien, 163 Tests gesamt" },
      { type: "internal", text: "Prisma-Migration: Tag, GameTag und Upload Modelle hinzugefügt" },
      { type: "internal", text: "SKILL.md: P3-28, P3-29, P3-30 als behoben markiert – nur noch 1 von 33 Findings offen" },
    ],
  },
  {
    version: "0.15.2",
    date: "2026-03-21",
    title: "Dokumentation, Pagination-Bestätigung & Tests",
    description: "CONCEPT.md aktualisiert (SessionRating-Modell, Statistics-API, Sessions-CRUD), Pagination bereits vorhanden bestätigt, public-link Tests ergänzt.",
    changes: [
      { type: "improvement", text: "CONCEPT.md: SessionRating-Modell, winningProposalId, Sessions-Detail-API und Statistics-API dokumentiert (P2-24)" },
      { type: "internal", text: "P1-9 Pagination: Alle 3 Listen-Endpoints hatten bereits ?page=X&limit=Y – SKILL.md korrigiert" },
      { type: "internal", text: "7 neue Unit Tests für public-link.ts (getClientBaseUrl Fallback-Kette) – 11 Test-Dateien, 139 Tests gesamt" },
      { type: "internal", text: "SKILL.md: P1-9, P2-24 als behoben markiert" },
    ],
  },
  {
    version: "0.15.1",
    date: "2026-03-21",
    title: "Code-Qualität: Typsicherheit, Validierung & Review-Fixes",
    description: "P2/P3-Findings umgesetzt: Alle any-Types durch typisierte Interfaces ersetzt, zentrale Validierungsfunktionen ergänzt, inline-Regex durch validateEmail ersetzt, SKILL.md aktualisiert.",
    changes: [
      { type: "improvement", text: "Alle 5 verbliebenen `any`-Types durch typisierte Interfaces ersetzt (BGGSearchResult, EventData, Html5Qrcode) (P2-18)" },
      { type: "feature", text: "Zentrale Validierungsfunktionen: validateEmail, validateUrl, validateDate, validateEnum in validation.ts (P2-43)" },
      { type: "improvement", text: "Inline-Email-Regex in register/route.ts durch zentrales validateEmail ersetzt" },
      { type: "internal", text: "28 neue Unit Tests für validateEmail, validateUrl, validateDate, validateEnum (132 Tests gesamt)" },
      { type: "internal", text: "SKILL.md: 12 weitere Findings als behoben markiert (P0-37/38, P1-10/11/41, P2-18/26/42/43, P3-32/34/36)" },
    ],
  },
  {
    version: "0.15.0",
    date: "2026-03-21",
    title: "Statistiken, Session-Detailseite & Rate-Limit Verbesserungen",
    description: "P0/P1-Findings umgesetzt: Statistik-Dashboard mit Charts, Session-Detailseite mit Bearbeiten/Löschen, und Rate-Limiting gegen Memory-Wachstum abgesichert.",
    changes: [
      { type: "feature", text: "Statistik-Dashboard mit Übersichtskarten, monatlicher Aktivität (Bar-Chart), Spieler-Rangliste und Top-10 meistgespielte Spiele (P1-10)" },
      { type: "feature", text: "Statistik-API: GET /api/statistics liefert Übersicht, meistgespielte Spiele, Spieler-Stats und monatliche Aktivität" },
      { type: "feature", text: "Session-Detailseite: /dashboard/sessions/[id] mit Spielinfo, Spieler-Tabelle, Bewertungen, Bearbeiten & Löschen (P1-11)" },
      { type: "feature", text: "Session-Edit-Seite: /dashboard/sessions/[id]/edit mit vorausgefülltem Formular" },
      { type: "feature", text: "Session-API: GET/PUT/DELETE /api/sessions/[id] mit Auth-Check, $transaction für Player-Updates" },
      { type: "improvement", text: "Rate-Limiting: maxSize-Guard (10.000 Einträge), LRU-Eviction bei Überlauf, Dokumentation für Serverless-Umgebungen (P1-41)" },
    ],
  },
  {
    version: "0.14.5",
    date: "2026-03-21",
    title: "Mega-Komponenten aufgeteilt",
    description: "Alle Dateien mit mehr als 400 Zeilen wurden systematisch in kleinere Subkomponenten aufgeteilt, um Wartbarkeit und Lesbarkeit zu verbessern.",
    changes: [
      { type: "internal", text: "games/import/page.tsx: 760 -> 280 Zeilen (CollectionImportDialog, GamePreviewCard extrahiert)" },
      { type: "internal", text: "profile-client.tsx: 588 -> 118 Zeilen (ProfileEditForm, PasswordChangeForm, ProfileActivityCards, ProfileMessagesCard extrahiert)" },
      { type: "internal", text: "date-poll-client.tsx: 731 -> 290 Zeilen (DatePollTypes, DateCreateForm, DatePollResetDialog, DateVotingMatrix extrahiert)" },
      { type: "internal", text: "voting/page.tsx: 693 -> 310 Zeilen (VotingTypes, ProposalRankingList, GameProposalPanel extrahiert)" },
      { type: "internal", text: "public/group/page.tsx: 471 -> 305 Zeilen (PublicGroupTypes, PublicPollCard, PublicDiscussionCard extrahiert)" },
      { type: "internal", text: "create-poll-form.tsx: 426 -> 159 Zeilen (GameOptionPicker extrahiert)" },
    ],
  },
  {
    version: "0.14.4",
    date: "2026-03-21",
    title: "Session-Bewertungen (SessionRating Modell)",
    description: "Session-Voting Bug behoben: Neues SessionRating-Modell ersetzt den fehlerhaften Versuch, Event-Votes für Sessions zu missbrauchen.",
    changes: [
      { type: "fix", text: "Session-Bewertungen funktionieren jetzt korrekt mit eigenem Datenmodell (1-5 Sterne + Kommentar) (P0-37)" },
      { type: "feature", text: "Bewertungen können aktualisiert werden (Upsert statt nur Create)" },
      { type: "internal", text: "Neues SessionRating-Modell in Prisma Schema mit eigener DB-Tabelle" },
    ],
  },
  {
    version: "0.14.3",
    date: "2026-03-21",
    title: "Bugfixes: Validierung, Close-Voting & .env.example",
    description: "Drei Bugs in der Eingabevalidierung behoben, Close-Voting zeigt jetzt auch BGG-only Gewinner korrekt an, .env.example auf PostgreSQL aktualisiert.",
    changes: [
      { type: "fix", text: "Close-Voting: BGG-only Spielvorschläge werden jetzt korrekt als Gewinner gespeichert und angezeigt (P0-38)" },
      { type: "fix", text: "Validierung: min=0 wurde fälschlich ignoriert (falsy-Check)" },
      { type: "fix", text: "Validierung: Maximallänge wird jetzt auf getrimmtem Text geprüft" },
      { type: "fix", text: "Validierung: Leerer String bei Zahlen wird nicht mehr als 0 akzeptiert" },
      { type: "internal", text: ".env.example auf PostgreSQL/SQL_DATABASE_URL aktualisiert" },
      { type: "internal", text: "Neues DB-Feld winningProposalId auf Event für BGG-only Gewinner" },
    ],
  },
  {
    version: "0.14.2",
    date: "2026-03-21",
    title: "Architektur: Mega-Komponenten aufgeteilt",
    description: "Große Komponenten (>400 Zeilen) in kleinere, wartbare Subkomponenten aufgeteilt. Verbessert Lesbarkeit, Testbarkeit und Entwicklerproduktivität.",
    changes: [
      { type: "internal", text: "monitoring-dashboard.tsx (906 → 144 Zeilen): Aufgeteilt in overview-tab, logs-tab und anomalies-tab" },
      { type: "internal", text: "series/[id]/page.tsx (976 → 592 Zeilen): Filter/Sort-Bar und Entry-Cards in eigene Komponenten extrahiert" },
      { type: "internal", text: "group-detail-client.tsx (989 → ~310 Zeilen): Poll-Voting in poll-card.tsx ausgelagert (vorherige Session)" },
      { type: "internal", text: "barcode-scanner.tsx (825 → ~340 Zeilen): Cover-Scan und Ergebnis-Panel in eigene Komponenten (vorherige Session)" },
      { type: "improvement", text: "Alle aufgeteilten Komponenten halten die 300-Zeilen-Regel ein" },
    ],
  },
  {
    version: "0.14.1",
    date: "2026-03-21",
    title: "Spielreihen-Details & Prod-DB-Backup",
    description: "Erweiterte Spielreihen-Einträge mit Spielzeit, Spieleranzahl, Punkte und Erfolgs-Tracking. Neues automatisches Backup-System für die Produktions-Datenbank vor jedem Push.",
    changes: [
      { type: "feature", text: "Spielreihen: Spielzeit, Spieleranzahl, Punkte und Erfolgreich/Nicht-geschafft pro Eintrag erfassbar" },
      { type: "feature", text: "Spielreihen: Aufklappbarer Detail-Bereich mit Inline-Editing (Speichern bei Fokusverlust)" },
      { type: "feature", text: "Spielreihen: Erfolgreich/Nicht-geschafft Badges und Zusammenfassungs-Icons in der Kartenansicht" },
      { type: "feature", text: "Prod-DB-Backup: Automatisches gzip-komprimiertes SQL-Backup vor jedem git push (Pre-Push Hook)" },
      { type: "feature", text: "npm run backup:prod – manuelles Backup der Produktions-Datenbank jederzeit ausführbar" },
      { type: "improvement", text: "Backup-Rotation: Maximal 10 Backups werden behalten, ältere automatisch aufgeräumt" },
      { type: "internal", text: "Prisma-Migration: 4 neue Felder auf GameSeriesEntry (playTimeMinutes, playerCount, score, successful)" },
      { type: "internal", text: "API: PUT /api/series/[id]/entries/[entryId] akzeptiert und validiert neue Felder, cleared bei Un-Play" },
    ],
  },
  {
    version: "0.14.0",
    date: "2026-03-21",
    title: "Code-Qualität, Sicherheit & Review-Evaluator",
    description: "Umfassendes Code-Review mit Sicherheitshärtung, Performance-Optimierung, Type-Safety-Verbesserungen und einem neuen automatischen Review-Evaluator für kontinuierliche Codequalität.",
    changes: [
      { type: "feature", text: "Review-Evaluator: automatisches Bewertungsskript für Code-Review-Findings mit 5 Dimensionen (Präzision, Aktualität, Abdeckung, Umsetzungsrate, Handlungsfähigkeit)" },
      { type: "feature", text: "Pre-Commit Hook prüft jetzt automatisch: Tests → Security Check → Review Evaluator" },
      { type: "feature", text: "Abstimmung beenden: neuer Button und API-Endpoint zum Schließen der Event-Abstimmung" },
      { type: "feature", text: "Datenschutz- und Nutzungsbedingungen-Seiten hinzugefügt (/terms, /privacy)" },
      { type: "feature", text: "Accessibility-Skill mit WCAG 2.1 AA Regeln dokumentiert" },
      { type: "improvement", text: "Input-Validierung mit Längenbegrenzungen auf allen öffentlichen und authentifizierten API-Routes" },
      { type: "improvement", text: "Rate-Limiting auf Auth-Endpoints (Registrierung, Passwort-Reset)" },
      { type: "improvement", text: "19 <img>-Tags auf next/image umgestellt für bessere Bildoptimierung" },
      { type: "improvement", text: "19 `any`-Types durch typisierte Interfaces ersetzt (SerializedGroup, BGGGameDetail u.a.)" },
      { type: "fix", text: "Datenbank-Transaktionen für Poll-Votes verhindern Datenverlust bei gleichzeitigen Abstimmungen" },
      { type: "fix", text: "voterName-Trim-Inkonsistenz in öffentlicher Vote-Route behoben" },
      { type: "internal", text: "7 neue Datenbank-Indizes auf häufig abgefragten Foreign Keys" },
      { type: "internal", text: "Composite-Index auf ApiLog für P95-Percentile-Query-Optimierung" },
      { type: "internal", text: "Geteilte getPendingInvites()-Query extrahiert (Deduplizierung Dashboard + Events)" },
      { type: "internal", text: "SQLite-DB-Dateien und Backups aus Git entfernt (.gitignore erweitert)" },
    ],
  },
  {
    version: "0.13.2",
    date: "2026-03-17",
    title: "Mobile Responsiveness",
    description: "Umfassendes Mobile-Audit mit Fixes auf allen Seiten – Buttons, Header, Formulare und Tabellen passen sich jetzt sauber an kleine Bildschirme an.",
    changes: [
      { type: "fix", text: "Spiele-Header: Buttons zeigen auf Mobile nur Icons, Text wird ab sm-Breakpoint eingeblendet" },
      { type: "fix", text: "Event-Detailseite: 5-Button-Overflow behoben – Buttons wrappen jetzt sauber auf Mobile" },
      { type: "fix", text: "Alle Seitenüberschriften von text-3xl auf text-2xl sm:text-3xl angepasst" },
      { type: "fix", text: "Metadata-Zeilen (Datum, Spieler, Dauer) wrappen jetzt korrekt mit flex-wrap" },
      { type: "fix", text: "Card-Header in Events, Sessions und Gruppen stacken vertikal auf Mobile" },
      { type: "fix", text: "Import-Seite: Spielvorschau-Bild und Text stacken auf Mobile übereinander" },
      { type: "fix", text: "Öffentliche Einladungsseite: Zusagen/Absagen-Buttons stacken auf Mobile" },
      { type: "fix", text: "Admin-Monitoring: Filter-Selects und Pagination passen sich an schmale Bildschirme an" },
      { type: "fix", text: "Formulare (Spiel anlegen/bearbeiten): Grid wechselt von 2 Spalten auf 1 Spalte auf Mobile" },
      { type: "improvement", text: "23 Dateien überarbeitet für durchgängig responsive Darstellung auf allen Geräten" },
    ],
  },
  {
    version: "0.13.1",
    date: "2026-03-16",
    title: "Bugfixes & Stabilität",
    description: "Behebung von Darstellungsproblemen bei Formularfeldern mit Icons und Verbesserung der Ladezustände im Dashboard.",
    changes: [
      { type: "fix", text: "Icon-Überlagerung in Eingabefeldern behoben – Platzhaltertext wird nicht mehr von Icons verdeckt" },
      { type: "fix", text: "CSS-Konflikt in der Input-Komponente behoben (tailwind-merge löst pl-Overrides jetzt korrekt auf)" },
      { type: "improvement", text: "Skeleton-Ladeanimation für das Dashboard hinzugefügt – kein weißer Bildschirm mehr beim Laden" },
      { type: "improvement", text: "Fehlerseite (Error Boundary) für den Dashboard-Bereich ergänzt mit \"Erneut versuchen\"-Button" },
      { type: "fix", text: "Datenbank-Verbindungstimeout ergänzt, um endloses Laden bei DB-Problemen zu verhindern" },
    ],
  },
  {
    version: "0.13.0",
    date: "2026-03-15",
    title: "Benutzerprofil & Passwort zurücksetzen",
    description: "Neues Benutzerprofil mit Kommunikationsübersicht und vollständiger Passwort-Zurücksetzen-Funktion per E-Mail.",
    changes: [
      { type: "feature", text: "Benutzerprofilseite mit bearbeitbarem Namen und E-Mail" },
      { type: "feature", text: "Passwort ändern direkt im Profil (mit Verifizierung des aktuellen Passworts)" },
      { type: "feature", text: "Kommunikationsübersicht: eigene Gruppen-Kommentare und Session-Notizen auf einen Blick" },
      { type: "feature", text: "Ausklappbare \"Meine Nachrichten\"-Sektion mit Verlinkung zu Gruppen und Sessions" },
      { type: "feature", text: "\"Passwort vergessen?\"-Funktion auf der Login-Seite" },
      { type: "feature", text: "Passwort-Reset per E-Mail mit zeitlich begrenztem Token (60 Min.)" },
      { type: "feature", text: "Neue Seite zum Zurücksetzen des Passworts mit Validierung" },
      { type: "improvement", text: "Benutzername in der Navbar ist jetzt klickbar und führt zum Profil" },
      { type: "improvement", text: "Übersicht über Events, Einladungen und Gruppen-Mitgliedschaften im Profil" },
    ],
  },
  {
    version: "0.12.0",
    date: "2026-03-15",
    title: "API Monitoring & Anomalie-Erkennung",
    description: "Neuer Admin-Bereich für API-Monitoring mit Live-Statistiken, Log-Analyse und automatischer Anomalie-Erkennung.",
    changes: [
      { type: "feature", text: "API Monitoring Dashboard mit Echtzeit-Übersicht (Requests, Fehlerrate, Antwortzeiten)" },
      { type: "feature", text: "Interaktive Charts für Request-Verlauf, Top-Endpoints und HTTP-Methoden-Verteilung" },
      { type: "feature", text: "Durchsuchbare und filterbare Log-Tabelle mit Paginierung" },
      { type: "feature", text: "Automatische Anomalie-Erkennung: Fehler-Spikes, langsame Endpoints, Auth-Probleme" },
      { type: "feature", text: "Health Score (0–100) mit Ampel-Bewertung des API-Zustands" },
      { type: "feature", text: "Auto-Refresh und Log-Bereinigung für alte Einträge" },
      { type: "internal", text: "API-Logging-Middleware für automatische Request-Erfassung in allen wichtigen Routes" },
    ],
  },
  {
    version: "0.11.0",
    date: "2026-03-15",
    title: "FAQ & Anleitung",
    description: "Eine neue FAQ-Seite erklärt alle Features und beantwortet häufige Fragen direkt in der App.",
    changes: [
      { type: "feature", text: "FAQ-Seite mit Anleitungen zu allen Features (Spiele, Events, Gruppen, Sessions)" },
      { type: "feature", text: "Aufklappbare Fragen & Antworten mit Accordion-Komponente" },
      { type: "feature", text: "Schnellnavigation zu den einzelnen Themenbereichen" },
      { type: "feature", text: "FAQ-Link in der Hauptnavigation" },
    ],
  },
  {
    version: "0.10.0",
    date: "2026-03-15",
    title: "Spielergruppen mit Abstimmungen",
    description: "Gruppen können jetzt Umfragen und Abstimmungen durchführen. Über einen öffentlichen Link können auch Nicht-Mitglieder abstimmen und kommentieren.",
    changes: [
      { type: "feature", text: "Spielergruppen erstellen und verwalten mit Mitgliederverwaltung" },
      { type: "feature", text: "Umfragen mit Einzel- oder Mehrfachwahl innerhalb von Gruppen" },
      { type: "feature", text: "Kommentare zu Abstimmungen und auf Gruppenebene" },
      { type: "feature", text: "Öffentlicher Link zum Teilen – Abstimmen und Kommentieren ohne Login" },
      { type: "feature", text: "Optionaler Passwortschutz für öffentliche Gruppenseiten" },
      { type: "feature", text: "Echtzeit-Balkendiagramme mit Stimmverteilung und Teilnehmernamen" },
      { type: "feature", text: "Spiele als Umfrageoptionen: aus eigener Sammlung wählen oder per BGG-Suche importieren" },
    ],
  },
  {
    version: "0.9.0",
    date: "2026-03-15",
    title: "Versionshistorie",
    description: "Die App hat jetzt eine eigene Versionshistorie, damit alle Neuerungen transparent nachvollziehbar sind.",
    changes: [
      { type: "feature", text: "Neue Changelog-Seite unter \"Versionen\" in der Navigation" },
      { type: "feature", text: "Versionsanzeige in der Navigationsleiste mit Link zur Historie" },
    ],
  },
  {
    version: "0.8.0",
    date: "2026-03-15",
    title: "E-Mail-System & Externe Einladungen",
    description: "Spieleabende lassen sich jetzt per E-Mail organisieren. Auch Personen ohne Account können eingeladen werden und direkt zusagen oder absagen.",
    changes: [
      { type: "feature", text: "E-Mail-Benachrichtigungen bei Event-Einladungen, Zu- und Absagen" },
      { type: "feature", text: "Externe Gäste per E-Mail einladen (kein Account nötig)" },
      { type: "feature", text: "Öffentliche Einladungs-Seite zum Zusagen/Absagen ohne Login" },
      { type: "feature", text: "Custom-Nachrichten an alle Teilnehmer mit frei wählbarem Betreff" },
      { type: "feature", text: "Erinnerungs-Mails an alle zugesagten Teilnehmer" },
      { type: "feature", text: "Teilnehmerliste mit Status auf der öffentlichen Event-Seite" },
      { type: "improvement", text: "Detaillierte Fehleranzeige wenn E-Mail-Versand fehlschlägt" },
    ],
  },
  {
    version: "0.7.0",
    date: "2026-03-15",
    title: "Navigation & Tabletop Indigo Design",
    description: "Die Navigation wurde komplett neu gebaut und ist jetzt auf allen Geräten zuverlässig sichtbar. Das Design wurde mit dem neuen Tabletop Indigo Theme aufgefrischt.",
    changes: [
      { type: "feature", text: "Neues Tabletop Indigo Theme mit durchgängigen Farbvariablen" },
      { type: "fix", text: "Navigation ist jetzt auf Desktop und Mobil immer sichtbar" },
      { type: "improvement", text: "Horizontales Scrollen der Navigation auf kleinen Bildschirmen" },
      { type: "improvement", text: "Icons auf Mobilgeräten, Icons + Text ab 1024px Breite" },
    ],
  },
  {
    version: "0.6.0",
    date: "2026-03-14",
    title: "Barcode-Scanner & Cover-Erkennung",
    description: "Spiele können jetzt blitzschnell per Barcode oder Foto des Covers importiert werden.",
    changes: [
      { type: "feature", text: "Barcode-Scanner zum Importieren von Spielen per EAN/UPC-Code" },
      { type: "feature", text: "Cover-Foto OCR: Spielname wird automatisch vom Cover erkannt" },
      { type: "feature", text: "Scanner direkt auf der Spiele-Übersicht und beim Anlegen neuer Spiele" },
      { type: "fix", text: "Verbesserte Namenserkennung und Fallback-Suche bei Barcodes" },
    ],
  },
  {
    version: "0.5.0",
    date: "2026-02-28",
    title: "Barrierefreiheit & Deployment",
    description: "Alle Farben und Kontraste wurden auf WCAG AA-Standard gebracht, damit die App für alle gut lesbar ist.",
    changes: [
      { type: "improvement", text: "Alle Farben erfüllen WCAG AA Kontrastanforderungen (4.5:1)" },
      { type: "improvement", text: "Semantische Tailwind-Farbvariablen statt fester Farbwerte" },
      { type: "internal", text: "Verbesserte Vercel-Deployment-Skripte mit automatischen Migrationen" },
    ],
  },
  {
    version: "0.4.0",
    date: "2026-02-27",
    title: "Terminabstimmung & Sammlungsimport",
    description: "Events haben jetzt eine Doodle-artige Terminabstimmung und die komplette BGG-Sammlung kann importiert werden.",
    changes: [
      { type: "feature", text: "Terminabstimmung für Events (ja / vielleicht / nein pro Datum)" },
      { type: "feature", text: "Komplette Spielesammlung aus BoardGameGeek importieren" },
      { type: "feature", text: "Gäste können ohne Account über den öffentlichen Link abstimmen" },
    ],
  },
  {
    version: "0.3.0",
    date: "2026-02-18",
    title: "UI-Verbesserungen & Admin",
    description: "Die Oberfläche wurde mit Toast-Benachrichtigungen und Spielbildern in der Abstimmung verbessert.",
    changes: [
      { type: "feature", text: "Admin-Nutzerverwaltung mit Rollen und Aktivierung/Deaktivierung" },
      { type: "feature", text: "Spielbilder werden in der Event-Abstimmung angezeigt" },
      { type: "improvement", text: "Toast-Benachrichtigungen statt Browser-Popups" },
      { type: "improvement", text: "Externe Bilder von BoardGameGeek werden korrekt geladen" },
    ],
  },
  {
    version: "0.2.0",
    date: "2026-02-18",
    title: "Vercel & PostgreSQL",
    description: "Die App läuft jetzt auf Vercel mit einer PostgreSQL-Datenbank für mehr Stabilität und Performance.",
    changes: [
      { type: "feature", text: "Hosting auf Vercel mit automatischem Deployment" },
      { type: "feature", text: "PostgreSQL-Datenbank statt SQLite" },
      { type: "feature", text: "Health-Check API für Monitoring" },
      { type: "internal", text: "Sicherheitsupdates für alle Abhängigkeiten" },
    ],
  },
  {
    version: "0.1.0",
    date: "2026-02-12",
    title: "Erste Version",
    description: "Die Grundversion von BoardGameTools mit Spieleverwaltung, Events und BoardGameGeek-Anbindung.",
    changes: [
      { type: "feature", text: "Spielesammlung verwalten (hinzufügen, bearbeiten, löschen)" },
      { type: "feature", text: "Spiele aus BoardGameGeek suchen und importieren" },
      { type: "feature", text: "Events erstellen mit Spielvorschlägen und Abstimmung" },
      { type: "feature", text: "Gruppen für regelmässige Spieleabende" },
      { type: "feature", text: "Benutzerregistrierung und Login" },
    ],
  },
];

export const currentVersion = changelog[0].version;
