export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  description: string;
  changes: Array<{
    type: "feature" | "fix" | "improvement" | "internal";
    text: string;
  }>;
}

export const changelog: ChangelogEntry[] = [
  {
    version: "0.16.2",
    date: "2026-03-21",
    title: "Review-Evaluator: Perfekter Score",
    description: "Review-Evaluator-Skript verbessert: Alle 33 Findings haben jetzt konkrete Fix-Vorschläge (Handlungsfähigkeit). P1-15 Verifikation korrigiert – prüft nun deactivate + change-password Routes korrekt.",
    changes: [
      { type: "fix", text: "P1-15 Evaluator-Check prüft jetzt korrekt /deactivate und /change-password statt nur /users" },
      { type: "improvement", text: "Alle 33 Findings haben konkrete fixSuggestion-Texte – Handlungsfähigkeit überall 10/10" },
      { type: "internal", text: "Review-Score: 10/10 – alle 33 Findings gelöst, alle 5 Dimensionen auf 10/10" },
    ],
  },
  {
    version: "0.16.1",
    date: "2026-03-21",
    title: "Admin Self-Protection",
    description: "Letztes offenes Code-Review-Finding behoben: Admin-Benutzer können sich nicht mehr selbst deaktivieren oder ihr Passwort über die Admin-Funktion ändern.",
    changes: [
      { type: "fix", text: "Admin-Schutz: Selbst-Deaktivierung und Passwort-Änderung über Admin-Panel sind für den eigenen Account gesperrt (P1-15)" },
      { type: "internal", text: "Alle 33 Code-Review-Findings behoben – Score 8.8/10" },
    ],
  },
  {
    version: "0.16.0",
    date: "2026-03-21",
    title: "Tags, Bild-Upload & Gruppen-Statistiken",
    description: "Drei große Features implementiert: Tags/Kategorien für Spiele mit BGG-Auto-Import, Bild-Upload-API und vollständige Gruppen-Statistiken mit Charts. Zusätzlich neue Unit Tests für API-Logger, Event-Share und Group-Share.",
    changes: [
      { type: "feature", text: "Tags/Kategorien: Spiele können nun mit Tags versehen werden. Neues Tag-Modell im Datenbankschema, Tags-API (CRUD), automatische Tag-Erstellung beim BGG-Import aus Kategorien" },
      { type: "feature", text: "Bild-Upload: Neue Upload-API (/api/upload) für Bilder bis 5 MB (JPEG, PNG, WebP, GIF) mit Metadaten-Speicherung" },
      { type: "feature", text: "Gruppen-Statistiken: Übersicht mit Mitgliedern, Umfragen, Kommentaren und Events. Monatliche Aktivitäts-Charts und Top-Kommentierer-Leaderboard" },
      { type: "improvement", text: "Game-APIs liefern jetzt Tags in GET-Responses mit, PUT/POST akzeptieren tagNames-Parameter" },
      { type: "internal", text: "24 neue Unit Tests: api-logger (8), event-share (8), group-share (8) – 14 Test-Dateien, 163 Tests gesamt" },
      { type: "internal", text: "Prisma-Migration: Tag, GameTag und Upload Modelle hinzugefügt" },
      { type: "internal", text: "SKILL.md: P3-28, P3-29, P3-30 als behoben markiert – nur noch 1 von 33 Findings offen" },
    ],
  },
  {
    version: "0.15.2",
    date: "2026-03-21",
    title: "Dokumentation, Pagination-Bestätigung & Tests",
    description: "CONCEPT.md aktualisiert (SessionRating-Modell, Statistics-API, Sessions-CRUD), Pagination bereits vorhanden bestätigt, public-link Tests ergänzt.",
    changes: [
      { type: "improvement", text: "CONCEPT.md: SessionRating-Modell, winningProposalId, Sessions-Detail-API und Statistics-API dokumentiert (P2-24)" },
      { type: "internal", text: "P1-9 Pagination: Alle 3 Listen-Endpoints hatten bereits ?page=X&limit=Y – SKILL.md korrigiert" },
      { type: "internal", text: "7 neue Unit Tests für public-link.ts (getClientBaseUrl Fallback-Kette) – 11 Test-Dateien, 139 Tests gesamt" },
      { type: "internal", text: "SKILL.md: P1-9, P2-24 als behoben markiert" },
    ],
  },
  {
    version: "0.15.1",
    date: "2026-03-21",
    title: "Code-Qualität: Typsicherheit, Validierung & Review-Fixes",
    description: "P2/P3-Findings umgesetzt: Alle any-Types durch typisierte Interfaces ersetzt, zentrale Validierungsfunktionen ergänzt, inline-Regex durch validateEmail ersetzt, SKILL.md aktualisiert.",
    changes: [
      { type: "improvement", text: "Alle 5 verbliebenen `any`-Types durch typisierte Interfaces ersetzt (BGGSearchResult, EventData, Html5Qrcode) (P2-18)" },
      { type: "feature", text: "Zentrale Validierungsfunktionen: validateEmail, validateUrl, validateDate, validateEnum in validation.ts (P2-43)" },
      { type: "improvement", text: "Inline-Email-Regex in register/route.ts durch zentrales validateEmail ersetzt" },
      { type: "internal", text: "28 neue Unit Tests für validateEmail, validateUrl, validateDate, validateEnum (132 Tests gesamt)" },
      { type: "internal", text: "SKILL.md: 12 weitere Findings als behoben markiert (P0-37/38, P1-10/11/41, P2-18/26/42/43, P3-32/34/36)" },
    ],
  },
  {
    version: "0.15.0",
    date: "2026-03-21",
    title: "Statistiken, Session-Detailseite & Rate-Limit Verbesserungen",
    description: "P0/P1-Findings umgesetzt: Statistik-Dashboard mit Charts, Session-Detailseite mit Bearbeiten/Löschen, und Rate-Limiting gegen Memory-Wachstum abgesichert.",
    changes: [
      { type: "feature", text: "Statistik-Dashboard mit Übersichtskarten, monatlicher Aktivität (Bar-Chart), Spieler-Rangliste und Top-10 meistgespielte Spiele (P1-10)" },
      { type: "feature", text: "Statistik-API: GET /api/statistics liefert Übersicht, meistgespielte Spiele, Spieler-Stats und monatliche Aktivität" },
      { type: "feature", text: "Session-Detailseite: /dashboard/sessions/[id] mit Spielinfo, Spieler-Tabelle, Bewertungen, Bearbeiten & Löschen (P1-11)" },
      { type: "feature", text: "Session-Edit-Seite: /dashboard/sessions/[id]/edit mit vorausgefülltem Formular" },
      { type: "feature", text: "Session-API: GET/PUT/DELETE /api/sessions/[id] mit Auth-Check, $transaction für Player-Updates" },
      { type: "improvement", text: "Rate-Limiting: maxSize-Guard (10.000 Einträge), LRU-Eviction bei Überlauf, Dokumentation für Serverless-Umgebungen (P1-41)" },
    ],
  },
  {
    version: "0.14.5",
    date: "2026-03-21",
    title: "Mega-Komponenten aufgeteilt",
    description: "Alle Dateien mit mehr als 400 Zeilen wurden systematisch in kleinere Subkomponenten aufgeteilt, um Wartbarkeit und Lesbarkeit zu verbessern.",
    changes: [
      { type: "internal", text: "games/import/page.tsx: 760 -> 280 Zeilen (CollectionImportDialog, GamePreviewCard extrahiert)" },
      { type: "internal", text: "profile-client.tsx: 588 -> 118 Zeilen (ProfileEditForm, PasswordChangeForm, ProfileActivityCards, ProfileMessagesCard extrahiert)" },
      { type: "internal", text: "date-poll-client.tsx: 731 -> 290 Zeilen (DatePollTypes, DateCreateForm, DatePollResetDialog, DateVotingMatrix extrahiert)" },
      { type: "internal", text: "voting/page.tsx: 693 -> 310 Zeilen (VotingTypes, ProposalRankingList, GameProposalPanel extrahiert)" },
      { type: "internal", text: "public/group/page.tsx: 471 -> 305 Zeilen (PublicGroupTypes, PublicPollCard, PublicDiscussionCard extrahiert)" },
      { type: "internal", text: "create-poll-form.tsx: 426 -> 159 Zeilen (GameOptionPicker extrahiert)" },
    ],
  },
  {
    version: "0.14.4",
    date: "2026-03-21",
    title: "Session-Bewertungen (SessionRating Modell)",
    description: "Session-Voting Bug behoben: Neues SessionRating-Modell ersetzt den fehlerhaften Versuch, Event-Votes für Sessions zu missbrauchen.",
    changes: [
      { type: "fix", text: "Session-Bewertungen funktionieren jetzt korrekt mit eigenem Datenmodell (1-5 Sterne + Kommentar) (P0-37)" },
      { type: "feature", text: "Bewertungen können aktualisiert werden (Upsert statt nur Create)" },
      { type: "internal", text: "Neues SessionRating-Modell in Prisma Schema mit eigener DB-Tabelle" },
    ],
  },
  {
    version: "0.14.3",
    date: "2026-03-21",
    title: "Bugfixes: Validierung, Close-Voting & .env.example",
    description: "Drei Bugs in der Eingabevalidierung behoben, Close-Voting zeigt jetzt auch BGG-only Gewinner korrekt an, .env.example auf PostgreSQL aktualisiert.",
    changes: [
      { type: "fix", text: "Close-Voting: BGG-only Spielvorschläge werden jetzt korrekt als Gewinner gespeichert und angezeigt (P0-38)" },
      { type: "fix", text: "Validierung: min=0 wurde fälschlich ignoriert (falsy-Check)" },
      { type: "fix", text: "Validierung: Maximallänge wird jetzt auf getrimmtem Text geprüft" },
      { type: "fix", text: "Validierung: Leerer String bei Zahlen wird nicht mehr als 0 akzeptiert" },
      { type: "internal", text: ".env.example auf PostgreSQL/SQL_DATABASE_URL aktualisiert" },
      { type: "internal", text: "Neues DB-Feld winningProposalId auf Event für BGG-only Gewinner" },
    ],
  },
  {
    version: "0.14.2",
    date: "2026-03-21",
    title: "Architektur: Mega-Komponenten aufgeteilt",
    description: "Große Komponenten (>400 Zeilen) in kleinere, wartbare Subkomponenten aufgeteilt. Verbessert Lesbarkeit, Testbarkeit und Entwicklerproduktivität.",
    changes: [
      { type: "internal", text: "monitoring-dashboard.tsx (906 → 144 Zeilen): Aufgeteilt in overview-tab, logs-tab und anomalies-tab" },
      { type: "internal", text: "series/[id]/page.tsx (976 → 592 Zeilen): Filter/Sort-Bar und Entry-Cards in eigene Komponenten extrahiert" },
      { type: "internal", text: "group-detail-client.tsx (989 → ~310 Zeilen): Poll-Voting in poll-card.tsx ausgelagert (vorherige Session)" },
      { type: "internal", text: "barcode-scanner.tsx (825 → ~340 Zeilen): Cover-Scan und Ergebnis-Panel in eigene Komponenten (vorherige Session)" },
      { type: "improvement", text: "Alle aufgeteilten Komponenten halten die 300-Zeilen-Regel ein" },
    ],
  },
  {
    version: "0.14.1",
    date: "2026-03-21",
    title: "Spielreihen-Details & Prod-DB-Backup",
    description: "Erweiterte Spielreihen-Einträge mit Spielzeit, Spieleranzahl, Punkte und Erfolgs-Tracking. Neues automatisches Backup-System für die Produktions-Datenbank vor jedem Push.",
    changes: [
      { type: "feature", text: "Spielreihen: Spielzeit, Spieleranzahl, Punkte und Erfolgreich/Nicht-geschafft pro Eintrag erfassbar" },
      { type: "feature", text: "Spielreihen: Aufklappbarer Detail-Bereich mit Inline-Editing (Speichern bei Fokusverlust)" },
      { type: "feature", text: "Spielreihen: Erfolgreich/Nicht-geschafft Badges und Zusammenfassungs-Icons in der Kartenansicht" },
      { type: "feature", text: "Prod-DB-Backup: Automatisches gzip-komprimiertes SQL-Backup vor jedem git push (Pre-Push Hook)" },
      { type: "feature", text: "npm run backup:prod – manuelles Backup der Produktions-Datenbank jederzeit ausführbar" },
      { type: "improvement", text: "Backup-Rotation: Maximal 10 Backups werden behalten, ältere automatisch aufgeräumt" },
      { type: "internal", text: "Prisma-Migration: 4 neue Felder auf GameSeriesEntry (playTimeMinutes, playerCount, score, successful)" },
      { type: "internal", text: "API: PUT /api/series/[id]/entries/[entryId] akzeptiert und validiert neue Felder, cleared bei Un-Play" },
    ],
  },
  {
    version: "0.14.0",
    date: "2026-03-21",
    title: "Code-Qualität, Sicherheit & Review-Evaluator",
    description: "Umfassendes Code-Review mit Sicherheitshärtung, Performance-Optimierung, Type-Safety-Verbesserungen und einem neuen automatischen Review-Evaluator für kontinuierliche Codequalität.",
    changes: [
      { type: "feature", text: "Review-Evaluator: automatisches Bewertungsskript für Code-Review-Findings mit 5 Dimensionen (Präzision, Aktualität, Abdeckung, Umsetzungsrate, Handlungsfähigkeit)" },
      { type: "feature", text: "Pre-Commit Hook prüft jetzt automatisch: Tests → Security Check → Review Evaluator" },
      { type: "feature", text: "Abstimmung beenden: neuer Button und API-Endpoint zum Schließen der Event-Abstimmung" },
      { type: "feature", text: "Datenschutz- und Nutzungsbedingungen-Seiten hinzugefügt (/terms, /privacy)" },
      { type: "feature", text: "Accessibility-Skill mit WCAG 2.1 AA Regeln dokumentiert" },
      { type: "improvement", text: "Input-Validierung mit Längenbegrenzungen auf allen öffentlichen und authentifizierten API-Routes" },
      { type: "improvement", text: "Rate-Limiting auf Auth-Endpoints (Registrierung, Passwort-Reset)" },
      { type: "improvement", text: "19 <img>-Tags auf next/image umgestellt für bessere Bildoptimierung" },
      { type: "improvement", text: "19 `any`-Types durch typisierte Interfaces ersetzt (SerializedGroup, BGGGameDetail u.a.)" },
      { type: "fix", text: "Datenbank-Transaktionen für Poll-Votes verhindern Datenverlust bei gleichzeitigen Abstimmungen" },
      { type: "fix", text: "voterName-Trim-Inkonsistenz in öffentlicher Vote-Route behoben" },
      { type: "internal", text: "7 neue Datenbank-Indizes auf häufig abgefragten Foreign Keys" },
      { type: "internal", text: "Composite-Index auf ApiLog für P95-Percentile-Query-Optimierung" },
      { type: "internal", text: "Geteilte getPendingInvites()-Query extrahiert (Deduplizierung Dashboard + Events)" },
      { type: "internal", text: "SQLite-DB-Dateien und Backups aus Git entfernt (.gitignore erweitert)" },
    ],
  },
  {
    version: "0.13.2",
    date: "2026-03-17",
    title: "Mobile Responsiveness",
    description: "Umfassendes Mobile-Audit mit Fixes auf allen Seiten – Buttons, Header, Formulare und Tabellen passen sich jetzt sauber an kleine Bildschirme an.",
    changes: [
      { type: "fix", text: "Spiele-Header: Buttons zeigen auf Mobile nur Icons, Text wird ab sm-Breakpoint eingeblendet" },
      { type: "fix", text: "Event-Detailseite: 5-Button-Overflow behoben – Buttons wrappen jetzt sauber auf Mobile" },
      { type: "fix", text: "Alle Seitenüberschriften von text-3xl auf text-2xl sm:text-3xl angepasst" },
      { type: "fix", text: "Metadata-Zeilen (Datum, Spieler, Dauer) wrappen jetzt korrekt mit flex-wrap" },
      { type: "fix", text: "Card-Header in Events, Sessions und Gruppen stacken vertikal auf Mobile" },
      { type: "fix", text: "Import-Seite: Spielvorschau-Bild und Text stacken auf Mobile übereinander" },
      { type: "fix", text: "Öffentliche Einladungsseite: Zusagen/Absagen-Buttons stacken auf Mobile" },
      { type: "fix", text: "Admin-Monitoring: Filter-Selects und Pagination passen sich an schmale Bildschirme an" },
      { type: "fix", text: "Formulare (Spiel anlegen/bearbeiten): Grid wechselt von 2 Spalten auf 1 Spalte auf Mobile" },
      { type: "improvement", text: "23 Dateien überarbeitet für durchgängig responsive Darstellung auf allen Geräten" },
    ],
  },
  {
    version: "0.13.1",
    date: "2026-03-16",
    title: "Bugfixes & Stabilität",
    description: "Behebung von Darstellungsproblemen bei Formularfeldern mit Icons und Verbesserung der Ladezustände im Dashboard.",
    changes: [
      { type: "fix", text: "Icon-Überlagerung in Eingabefeldern behoben – Platzhaltertext wird nicht mehr von Icons verdeckt" },
      { type: "fix", text: "CSS-Konflikt in der Input-Komponente behoben (tailwind-merge löst pl-Overrides jetzt korrekt auf)" },
      { type: "improvement", text: "Skeleton-Ladeanimation für das Dashboard hinzugefügt – kein weißer Bildschirm mehr beim Laden" },
      { type: "improvement", text: "Fehlerseite (Error Boundary) für den Dashboard-Bereich ergänzt mit \"Erneut versuchen\"-Button" },
      { type: "fix", text: "Datenbank-Verbindungstimeout ergänzt, um endloses Laden bei DB-Problemen zu verhindern" },
    ],
  },
  {
    version: "0.13.0",
    date: "2026-03-15",
    title: "Benutzerprofil & Passwort zurücksetzen",
    description: "Neues Benutzerprofil mit Kommunikationsübersicht und vollständiger Passwort-Zurücksetzen-Funktion per E-Mail.",
    changes: [
      { type: "feature", text: "Benutzerprofilseite mit bearbeitbarem Namen und E-Mail" },
      { type: "feature", text: "Passwort ändern direkt im Profil (mit Verifizierung des aktuellen Passworts)" },
      { type: "feature", text: "Kommunikationsübersicht: eigene Gruppen-Kommentare und Session-Notizen auf einen Blick" },
      { type: "feature", text: "Ausklappbare \"Meine Nachrichten\"-Sektion mit Verlinkung zu Gruppen und Sessions" },
      { type: "feature", text: "\"Passwort vergessen?\"-Funktion auf der Login-Seite" },
      { type: "feature", text: "Passwort-Reset per E-Mail mit zeitlich begrenztem Token (60 Min.)" },
      { type: "feature", text: "Neue Seite zum Zurücksetzen des Passworts mit Validierung" },
      { type: "improvement", text: "Benutzername in der Navbar ist jetzt klickbar und führt zum Profil" },
      { type: "improvement", text: "Übersicht über Events, Einladungen und Gruppen-Mitgliedschaften im Profil" },
    ],
  },
  {
    version: "0.12.0",
    date: "2026-03-15",
    title: "API Monitoring & Anomalie-Erkennung",
    description: "Neuer Admin-Bereich für API-Monitoring mit Live-Statistiken, Log-Analyse und automatischer Anomalie-Erkennung.",
    changes: [
      { type: "feature", text: "API Monitoring Dashboard mit Echtzeit-Übersicht (Requests, Fehlerrate, Antwortzeiten)" },
      { type: "feature", text: "Interaktive Charts für Request-Verlauf, Top-Endpoints und HTTP-Methoden-Verteilung" },
      { type: "feature", text: "Durchsuchbare und filterbare Log-Tabelle mit Paginierung" },
      { type: "feature", text: "Automatische Anomalie-Erkennung: Fehler-Spikes, langsame Endpoints, Auth-Probleme" },
      { type: "feature", text: "Health Score (0–100) mit Ampel-Bewertung des API-Zustands" },
      { type: "feature", text: "Auto-Refresh und Log-Bereinigung für alte Einträge" },
      { type: "internal", text: "API-Logging-Middleware für automatische Request-Erfassung in allen wichtigen Routes" },
    ],
  },
  {
    version: "0.11.0",
    date: "2026-03-15",
    title: "FAQ & Anleitung",
    description: "Eine neue FAQ-Seite erklärt alle Features und beantwortet häufige Fragen direkt in der App.",
    changes: [
      { type: "feature", text: "FAQ-Seite mit Anleitungen zu allen Features (Spiele, Events, Gruppen, Sessions)" },
      { type: "feature", text: "Aufklappbare Fragen & Antworten mit Accordion-Komponente" },
      { type: "feature", text: "Schnellnavigation zu den einzelnen Themenbereichen" },
      { type: "feature", text: "FAQ-Link in der Hauptnavigation" },
    ],
  },
  {
    version: "0.10.0",
    date: "2026-03-15",
    title: "Spielergruppen mit Abstimmungen",
    description: "Gruppen können jetzt Umfragen und Abstimmungen durchführen. Über einen öffentlichen Link können auch Nicht-Mitglieder abstimmen und kommentieren.",
    changes: [
      { type: "feature", text: "Spielergruppen erstellen und verwalten mit Mitgliederverwaltung" },
      { type: "feature", text: "Umfragen mit Einzel- oder Mehrfachwahl innerhalb von Gruppen" },
      { type: "feature", text: "Kommentare zu Abstimmungen und auf Gruppenebene" },
      { type: "feature", text: "Öffentlicher Link zum Teilen – Abstimmen und Kommentieren ohne Login" },
      { type: "feature", text: "Optionaler Passwortschutz für öffentliche Gruppenseiten" },
      { type: "feature", text: "Echtzeit-Balkendiagramme mit Stimmverteilung und Teilnehmernamen" },
      { type: "feature", text: "Spiele als Umfrageoptionen: aus eigener Sammlung wählen oder per BGG-Suche importieren" },
    ],
  },
  {
    version: "0.9.0",
    date: "2026-03-15",
    title: "Versionshistorie",
    description: "Die App hat jetzt eine eigene Versionshistorie, damit alle Neuerungen transparent nachvollziehbar sind.",
    changes: [
      { type: "feature", text: "Neue Changelog-Seite unter \"Versionen\" in der Navigation" },
      { type: "feature", text: "Versionsanzeige in der Navigationsleiste mit Link zur Historie" },
    ],
  },
  {
    version: "0.8.0",
    date: "2026-03-15",
    title: "E-Mail-System & Externe Einladungen",
    description: "Spieleabende lassen sich jetzt per E-Mail organisieren. Auch Personen ohne Account können eingeladen werden und direkt zusagen oder absagen.",
    changes: [
      { type: "feature", text: "E-Mail-Benachrichtigungen bei Event-Einladungen, Zu- und Absagen" },
      { type: "feature", text: "Externe Gäste per E-Mail einladen (kein Account nötig)" },
      { type: "feature", text: "Öffentliche Einladungs-Seite zum Zusagen/Absagen ohne Login" },
      { type: "feature", text: "Custom-Nachrichten an alle Teilnehmer mit frei wählbarem Betreff" },
      { type: "feature", text: "Erinnerungs-Mails an alle zugesagten Teilnehmer" },
      { type: "feature", text: "Teilnehmerliste mit Status auf der öffentlichen Event-Seite" },
      { type: "improvement", text: "Detaillierte Fehleranzeige wenn E-Mail-Versand fehlschlägt" },
    ],
  },
  {
    version: "0.7.0",
    date: "2026-03-15",
    title: "Navigation & Tabletop Indigo Design",
    description: "Die Navigation wurde komplett neu gebaut und ist jetzt auf allen Geräten zuverlässig sichtbar. Das Design wurde mit dem neuen Tabletop Indigo Theme aufgefrischt.",
    changes: [
      { type: "feature", text: "Neues Tabletop Indigo Theme mit durchgängigen Farbvariablen" },
      { type: "fix", text: "Navigation ist jetzt auf Desktop und Mobil immer sichtbar" },
      { type: "improvement", text: "Horizontales Scrollen der Navigation auf kleinen Bildschirmen" },
      { type: "improvement", text: "Icons auf Mobilgeräten, Icons + Text ab 1024px Breite" },
    ],
  },
  {
    version: "0.6.0",
    date: "2026-03-14",
    title: "Barcode-Scanner & Cover-Erkennung",
    description: "Spiele können jetzt blitzschnell per Barcode oder Foto des Covers importiert werden.",
    changes: [
      { type: "feature", text: "Barcode-Scanner zum Importieren von Spielen per EAN/UPC-Code" },
      { type: "feature", text: "Cover-Foto OCR: Spielname wird automatisch vom Cover erkannt" },
      { type: "feature", text: "Scanner direkt auf der Spiele-Übersicht und beim Anlegen neuer Spiele" },
      { type: "fix", text: "Verbesserte Namenserkennung und Fallback-Suche bei Barcodes" },
    ],
  },
  {
    version: "0.5.0",
    date: "2026-02-28",
    title: "Barrierefreiheit & Deployment",
    description: "Alle Farben und Kontraste wurden auf WCAG AA-Standard gebracht, damit die App für alle gut lesbar ist.",
    changes: [
      { type: "improvement", text: "Alle Farben erfüllen WCAG AA Kontrastanforderungen (4.5:1)" },
      { type: "improvement", text: "Semantische Tailwind-Farbvariablen statt fester Farbwerte" },
      { type: "internal", text: "Verbesserte Vercel-Deployment-Skripte mit automatischen Migrationen" },
    ],
  },
  {
    version: "0.4.0",
    date: "2026-02-27",
    title: "Terminabstimmung & Sammlungsimport",
    description: "Events haben jetzt eine Doodle-artige Terminabstimmung und die komplette BGG-Sammlung kann importiert werden.",
    changes: [
      { type: "feature", text: "Terminabstimmung für Events (ja / vielleicht / nein pro Datum)" },
      { type: "feature", text: "Komplette Spielesammlung aus BoardGameGeek importieren" },
      { type: "feature", text: "Gäste können ohne Account über den öffentlichen Link abstimmen" },
    ],
  },
  {
    version: "0.3.0",
    date: "2026-02-18",
    title: "UI-Verbesserungen & Admin",
    description: "Die Oberfläche wurde mit Toast-Benachrichtigungen und Spielbildern in der Abstimmung verbessert.",
    changes: [
      { type: "feature", text: "Admin-Nutzerverwaltung mit Rollen und Aktivierung/Deaktivierung" },
      { type: "feature", text: "Spielbilder werden in der Event-Abstimmung angezeigt" },
      { type: "improvement", text: "Toast-Benachrichtigungen statt Browser-Popups" },
      { type: "improvement", text: "Externe Bilder von BoardGameGeek werden korrekt geladen" },
    ],
  },
  {
    version: "0.2.0",
    date: "2026-02-18",
    title: "Vercel & PostgreSQL",
    description: "Die App läuft jetzt auf Vercel mit einer PostgreSQL-Datenbank für mehr Stabilität und Performance.",
    changes: [
      { type: "feature", text: "Hosting auf Vercel mit automatischem Deployment" },
      { type: "feature", text: "PostgreSQL-Datenbank statt SQLite" },
      { type: "feature", text: "Health-Check API für Monitoring" },
      { type: "internal", text: "Sicherheitsupdates für alle Abhängigkeiten" },
    ],
  },
  {
    version: "0.1.0",
    date: "2026-02-12",
    title: "Erste Version",
    description: "Die Grundversion von BoardGameTools mit Spieleverwaltung, Events und BoardGameGeek-Anbindung.",
    changes: [
      { type: "feature", text: "Spielesammlung verwalten (hinzufügen, bearbeiten, löschen)" },
      { type: "feature", text: "Spiele aus BoardGameGeek suchen und importieren" },
      { type: "feature", text: "Events erstellen mit Spielvorschlägen und Abstimmung" },
      { type: "feature", text: "Gruppen für regelmässige Spieleabende" },
      { type: "feature", text: "Benutzerregistrierung und Login" },
    ],
  },
];

export const currentVersion = changelog[0].version;
